### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by MrAugMyo** [facebook/facebook-android-sdk#1049]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)

### Goals

Facebook

### Expected results

[https://www.facebook.com/aungmyo.zeo/](url)

### Code samples & details

```java
https://m.facebook.com/100016695042794
```

**Comment by linmx0130** [comment]
Not a valid issue. Close it.
