### ISSUE TITLE
ShareLinkContent quote value not displayed on Messenger.

### ISSUE THREAD

**Issue by heitorcolangelo** [facebook/facebook-android-sdk#571]
**SDK VERSION: 5.4.0**

I'm setting the `quote` in my `ShareLinkContent` object:

```
val shareLinkContent = ShareLinkContent.Builder().apply {
    setContentUrl(Uri.parse(linkToShare))
    setQuote(contentMessage)
}.build()
```
And then, depending on the user's choice, sharing this on Facebook application:
```
ShareDialog(this).show(shareLinkContent)
```
or using Messenger application:
```
MessageDialog(this).show(shareLinkContent)
```

The `quote` message is displayed properly on Facebook application, but on Messenger application, only the link is displayed.
Is there any catch to show the `quote` text on Messenger application? Is that even possible?

**Comment by heitorcolangelo** [comment]
No one answered this issue in 5 months, and now you use a bot to close the issue saying that it was inactivity? Have you guys at least investigate that?

**Comment by aleksiy805** [comment]
It really doesn't work even now

**Comment by Mxiim** [comment]
I was trying to look in the changelog(https://developers.facebook.com/docs/messenger-platform/changelog/) and the code for MessengerDialog and it seems to be as it is deprecated, as well as ShareLinkContent has a comment saying it will be deprecated in Nov, 2019 and no longer works.
If I misunderstood that, then please submit a bug here https://developers.facebook.com/support/bugs/ 
with more details.

**Comment by Chamika-Perera-Incentivio** [comment]
Is there any solution for this issue?
