### ISSUE TITLE
The crash due to Facebook SDK on Android 4.X

### ISSUE THREAD

**Issue by YanCorey** [facebook/facebook-android-sdk#573]
Here is the crash log:
Fatal Exception: java.lang.AbstractMethodError
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.facebook.appevents.p.g.a(InAppPurchaseEventManager.java:68)
com.facebook.appevents.p.g.c(InAppPurchaseEventManager.java:3)
com.facebook.appevents.p.g.b(InAppPurchaseEventManager.java:23)
com.facebook.appevents.p.g.b(InAppPurchaseEventManager.java:21)
com.facebook.appevents.p.f$b$a.run(InAppPurchaseActivityLifecycleTracker.java:2)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
java.lang.Thread.run(Thread.java:856)

**Comment by dreamolight** [comment]
Hi @YanCorey , most likely it's fixed in newer versions, could you test against latest version which is 5.5.1?

**Comment by YanCorey** [comment]
All right!

**Comment by dreamolight** [comment]
Closing it for now, will reopen it if you could still reproduce the issue.

**Comment by YanCorey** [comment]
This crash still exists in version 5.5.1.
