### ISSUE TITLE
This crash still exists in version 5.5.1.

### ISSUE THREAD

**Issue by YanCorey** [facebook/facebook-android-sdk#575]
This crash still exists in version 5.5.1.

_Originally posted by @YanCorey in https://github.com/facebook/facebook-android-sdk/issues/573#issuecomment-529720217_

**Comment by YanCorey** [comment]
I fell back to 5.1.1 and there was no such crash. I want to ask, I want to go up to 5.5.1, how can I solve this problem?

**Comment by thanakitskp** [comment]
จะแก้ไขยังไง

**Comment by dreamolight** [comment]
Please continue the conversation in original issue so we can have full context there.
