### ISSUE TITLE
Memory leak in CodeLessManager

### ISSUE THREAD

**Issue by mahendra0203** [facebook/facebook-android-sdk#576]
I am seeing memory leaks in CodeLessManager in the new facebook android sdk.

Log details is pasted below.

LeakingInstance(referenceKey=d675b1b3-9c05-47b8-9601-84ef86bab3bb, referenceName=, instanceClassName=com.onefc.android.app.ui.main.ContainerActivity, watchDurationMillis=5352, excludedLeak=false, leakTrace=
┬
├─ com.facebook.appevents.codeless.CodelessManager
│    Leaking: NO (a class is always reachable)
│    ↓ static CodelessManager.viewIndexingTrigger
│                             ~~~~~~~~~~~~~~~~~~~
├─ com.facebook.appevents.codeless.ViewIndexingTrigger
│    Leaking: UNKNOWN
│    ↓ ViewIndexingTrigger.mListener
│                          ~~~~~~~~~
├─ com.facebook.appevents.codeless.CodelessManager$1$1
│    Leaking: UNKNOWN
│    Anonymous class implementing com.facebook.appevents.codeless.ViewIndexingTrigger$OnShakeListener
│    ↓ CodelessManager$1$1.this$0
│                          ~~~~~~
├─ com.facebook.appevents.codeless.CodelessManager$1
│    Leaking: UNKNOWN
│    Anonymous class implementing com.facebook.internal.FeatureManager$Callback
│    ↓ CodelessManager$1.val$activity
│                        ~~~~~~~~~~~~
╰→ com.onefc.android.app.ui.main.ContainerActivity
​     Leaking: YES (Activity#mDestroyed is true)
, retainedHeapSize=null)

**Comment by KylinChang** [comment]
The issue should be addressed in v5.5.2
