### ISSUE TITLE
GameRequestDialog asks for login even if the user is connected

### ISSUE THREAD

**Issue by vincent-schirmann** [facebook/facebook-android-sdk#578]
Although the user is connected (via the Facebook app installed) when I try to send a apprequest, the webDialog asks for login.
When the auth in the webdialog is done, every GameRequestDialog works during the session.
When I quit and run the game again, the problem occurs again.

The RPSSample project has the same issue.

Thanks in advance

Edit : I've found some users facing the same problem on Android and iOS too, so it's maybe not an issue of the SDK...

**Comment by youstheara** [comment]
forgot  password account

**Comment by KylinChang** [comment]
Hi @vincent-schirmann , @youstheara , this is expected and it prevents malicious apps from access to user data.

**Comment by sreesujith** [comment]
Hello @vincent-schirmann,

Are you able to resolve the issue?

**Comment by vincent-schirmann** [comment]
Hi @sreesujith ,
unfortunately no, and we can not expect any help from the Facebook side as we can see here (unless maybe if hou have a Business Partner at Facebook) :
https://developers.facebook.com/support/bugs/323761688312312/

**Comment by lrl8931589** [comment]
Hello, I met the same problem, have you solved it?
