### ISSUE TITLE
errorMessage: (#4) Application request limit reached} While Login

### ISSUE THREAD

**Issue by applaner** [facebook/facebook-android-sdk#582]
E/GraphResponse: {HttpStatus: 403, errorCode: 4, subErrorCode: -1, errorType: OAuthException, errorMessage: (#4) Application request limit reached}
implementation 'com.facebook.android:facebook-login:[5,6)'
While doing login

**Comment by itsmasud** [comment]
I am also having the same error.

**Comment by wajahatshaw** [comment]
Did you guys find the solution for this? I'm having the error.

**Comment by khunzohn** [comment]
Any update on this? I'm facing the same.
