### ISSUE TITLE
Duplicate resources error on building a fat aar

### ISSUE THREAD

**Issue by huy2368** [facebook/facebook-android-sdk#584]
Hi team,
I'm trying to create a fat aar which contains some other aar files. Below is the guide I based on:
    https://github.com/kezong/fat-aar-android

My build configurations:
    - Java Version: 1.8.0_122
    - Android SDK Version: 28
    - Installation Platform & Verison:  FacebookSDK for Android 5.2.0

There are many errors in merging resources step come from the conflict between Facebook-Common.aar and Facebook-Login.aar.
I see resource files: values-*.xml are same on both sides.
For example:
    [string/com_facebook_device_auth_instructions] build\intermediates\exploded-aar\facebook-login\release\res\values\values.xml
    [string/com_facebook_device_auth_instructions] build\intermediates\exploded-aar\facebook-common\release\res\values\values.xml:
    Error: Duplicate resources

After modifying string values in Facebook-Common and Facebook-Login and rebuild two SDKs, I can build my fat aar successfully.
![image](https://user-images.githubusercontent.com/39150262/65668712-6a898d00-e06c-11e9-9c87-14b3e7c0c3d4.png)

I dont know those duplicate strings are here with any purpose.

**Comment by dreamolight** [comment]
Closing this as we don't provide support on this third party tool. It'd be better to submit an issue there as we haven't received any bug report regarding duplicate resources.

**Comment by vikram-kodag** [comment]
Adding "android.disableResourceValidation=true" to "gradle.properties" can do a trick to skip the exception, but is not recommended.
