### ISSUE TITLE
Feature Request: Update the documentation to remove Facebook lite as login method

### ISSUE THREAD

**Issue by bangarharshit** [facebook/facebook-android-sdk#588]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

Facebook lite is not supported https://github.com/facebook/facebook-android-sdk/issues/585 but is mentioned in the official [doc](https://developers.facebook.com/docs/facebook-login/overview) and various [other docs](https://developers.facebook.com/blog/post/v2/2016/10/27/login-for-tv-and-android/). It is causing a lot of confusion so please update the docs to remove the same.

**Comment by bangarharshit** [comment]
Yes. It needs an input from Facebook team. Still waiting for the reply.

**Comment by maghli** [comment]
مرحبا فريق دعم العملاء ،
بادئ ذي بدء ، أود أن أشكرك مقدمًا على مساعدتكم ودعمكم ...
مشكلتي هي أن حساب FaceBook الخاص بأصدقائي تم تعطيله وأود أن أطلب منك إعادة تنشيطه مرة أخرى.
لم تكن القواعد واللوائح في FaceBook التي تحدد استخدام ميزات معينة واضحة تمامًا لنفسها ، لكن بعد إلقاء نظرة عليها في قسم مركز المساعدة - البريد العشوائي ، اكتشفت سبب تعطيل حساباتهم وأؤكد لكم أن السبب حظر حسابات أنفسهم ، وهو الاستخدام الخاطئ لميزة الرسائل وفقًا للوائح الخاصة بك ، لم يكن بأي حال من الأحوال خارجًا عن إرادتهم الشريرة وكان عن طريق الصدفة تمامًا
سيكونون ممتنين حقًا إذا كان من الممكن إعادة تنشيط حساباتهم الذاتية مرةً أخرى ، مما يعدك بتجنب الاستخدام غير الصحيح لميزات Face Book في المستقبل
معلومات حساب Face Face Face:
