### ISSUE TITLE
Could the sdk support android 14?

### ISSUE THREAD

**Issue by flyxianable** [facebook/facebook-android-sdk#600]
## Checklist

- [ ] I've updated to the latest released version of the SDK
- [ ] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [ ] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [ ] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

I hope the sdk support android 14 version

## Expected Results

What do you expect to happen?

## Code Samples & Details

Please provide a code sample, as well as any additional details, to help us track down the issue. If you can provide a link to a test project that allows us to reproduce the issue, this helps us immensely in both the speed and quality of the fix.

**Note:** Remember to format your code for readability:

```swift
// INSERT YOUR CODE HERE

var example = "Example code"
```

**Comment by jingping2015** [comment]
Current minimal support version is 15. You can find it here https://developers.facebook.com/docs/android/
