### ISSUE TITLE
Request to add AndroidX repository

### ISSUE THREAD

**Issue by hashdogcn** [facebook/facebook-android-sdk#609]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Request to add AndroidX repository`

## Goals

Sdk supports AndroidX

## Expected Results

I hope that Facebook can support AndroidX. Some libraries used by our company support AndroidX. However, we also use Facebook's login function, but currently Facebook's sdk does not support AndroidX, which makes us unable to use some components. It is very troublesome.

**Comment by Wouldve** [comment]
I have not yet received my Android X
