### ISSUE TITLE
java.lang.IllegalArgumentException  Service not registered in GoogleAdServiceConnection

### ISSUE THREAD

**Issue by YoungBill** [facebook/facebook-android-sdk#615]
Our project has a large area crash after upgrading 5.9.0 sdk on 11.1.
Below is the error stack:

android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
--
android.app.ContextImpl.unbindService(ContextImpl.java:1781)
android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
com.facebook.internal.AttributionIdentifiers.com.facebook.internal.AttributionIdentifiers cacheAndReturnIdentifiers(com.facebook.internal.AttributionIdentifiers)(Unknown Source:200)
##_parent_##1##_parent_##
##_child_## java.lang.String getAndroidAdvertiserId()##_child_##
com.facebook.marketing.internal.RemoteConfigManager$1.run(Unknown Source:8)

**Comment by 1074736711** [comment]
@jingping2015 
Same Problem！
We also have so many crashes after compiling with android sdk 5.9.0
10% of users have crashes every day。

**Comment by Goach** [comment]
Same Problem！

**Comment by gslovemy** [comment]
same problems
