### ISSUE TITLE
Can't use Facebook to log into this app or website

### ISSUE THREAD

**Issue by alexander-koval** [facebook/facebook-android-sdk#616]
Hi guys. I clone repository and start FBLoginSample project. 
Compile and run on my android device with installed Facebook app. Than I push the button "Continue with Facebook" and got an error "Login Error: There is an error in logging you into this application. Please try again later."
Than I change facebook_app_id and fb_login_protocol_scheme to my app ids and i've got an error "You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook Login"
Tell me please what should I do to make it work?

**Comment by tafelnl** [comment]
I experienced the first issue you mentioned as well.

If you already uploaded your app to the playstore and enabled "app signing by Google Play" there is a solution (at least this worked for me):

- login into you play console
- click on the app
- now on the left side click "release management"
- click "App signing"
- under "App signing certificate" copy the SHA-1 certificate fingerprint
- go to http://tomeko.net/online_tools/hex_to_base64.php
- paste the SHA-1 in the first field
- copy the text in input field under "Output (base64)"
- now open developer.facebook.com/apps
- click your app
- on the left side navigate to "Settings" -> "Basic"
- past the Base64 text here under key hashes
![image](https://user-images.githubusercontent.com/35837839/68941932-7c9fc600-07a7-11ea-9fa1-af59efb263f1.png)

That should fix the issue.
