### ISSUE TITLE
Feature Request: Update com.android.support dependency from 27.0.2 to 28.0.0

### ISSUE THREAD

**Issue by BurningAXE** [facebook/facebook-android-sdk#621]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

Submit an app update that uses com.facebook.android:facebook-login

Details:
Google Play Console now requires all new apps and app updates to have targetSdkVersion 28+
This goes hand in hand with using version 28+ of com.android.support. However, the latest version of facebook login (com.facebook.android:facebook-login:5.9.0) has a dependency to com.android.support:customtabs:27.0.2 which creates a version conflict. The error Gradle gives is:

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 27.0.2. Examples include com.android.support:animated-vector-drawable:28.0.0 and com.android.support:customtabs:27.0.2 less... (⌘F1)
Inspection info:There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).
Issue id: GradleCompatible

**This effectively prevents apps that use facebook sdk from being submitted/updated on Google Play!**

**Comment by BurningAXE** [comment]
Issue is still relevant AFAIK.

**Comment by mdcdeveloper** [comment]
I would increase the request to androidX, drop this legacy dependency once and for all.. How long do we have to wait for a "Right click + Convert to AndroidX"?

**Comment by andretietz** [comment]
Updating from `com.android.support` to `androidx` would be even more helpful. With that we could disable the jetifier and have faster builds.
