### ISSUE TITLE
How to disable Codeless Events and/or Analytics because of crashes?

### ISSUE THREAD

**Issue by zenith-jacob** [facebook/facebook-android-sdk#625]
Using latest 7.18.0

Let's end this coding disaster, after nearly a year.

Here are the issues that make us impossible to make business with you:
https://github.com/facebook/facebook-sdk-for-unity/issues/347
https://github.com/facebook/facebook-sdk-for-unity/issues/345#issue-515220019
https://github.com/facebook/facebook-sdk-for-unity/issues/245

They are all related to Codeless Events that you have enforced during the latest updates.

Using older SDKs isn't possible because you have enforced an upgrade.
Using 7.17 is not possible because it's not compatible with Facebook Audience Network:
https://github.com/facebook/facebook-sdk-for-unity/issues/348
https://github.com/facebook/facebook-sdk-for-unity/issues/278
7.18 fixed the FAN issue and created 14 others.

This leaves us with NO OPTIONS AT ALL. We can't use the SDK in any version so we have to remove it and start loosing money (both we, and you), because of the lack of support from your side.

You keep adding useless changes like this codeless stuff without testing it properly and then we, developers have to spend nights on customizing the SDK so it doesn't crush.

I think you forgot that you are working on a library that runs on billions of devices on this planet.

How is this possible, that even if we disabled "Automatic Event Sending" through manifest and through Unity's configuration, this library is still working in background making and sending screenshots somewhere?

**So, how to disable Codeless Events, so they don't make screenshots, send unwanted events and don't even exist in memory?**

**Comment by chao2zhang** [comment]
I recently ran into this issue with Android integration of Facebook Android SDK. 

- This codeless poses risks in app stability by using [Reflection](https://github.com/facebook/facebook-android-sdk/blob/main/facebook-core/src/main/java/com/facebook/appevents/codeless/internal/ViewHierarchy.kt#L405) and periodically checking [View Hierarchy](https://github.com/facebook/facebook-android-sdk/blob/main/facebook-core/src/main/java/com/facebook/appevents/codeless/ViewIndexer.kt)
- Additionally, uploading [screenshots](https://github.com/facebook/facebook-android-sdk/blob/main/facebook-core/src/main/java/com/facebook/appevents/codeless/ViewIndexer.kt#L90) of the App is an obvious violation of user privacy.

I do not think this issue should be left unattended and marked as stale. Our team is currently using `CodelessManager.disable()` as a workaround but I would prefer the [documentation](https://developers.facebook.com/docs/app-events/codeless-app-events#implement-the-codeless-app-event-feature) to be explicit on how to opt-out (or change this feature to be opt-in)
