### ISSUE TITLE
Fatal Exception: java.lang.SecurityException !@Too many alarms (500)

### ISSUE THREAD

**Issue by vhontar** [facebook/facebook-android-sdk#627]
## Goals
I want to avoid background crashes which happened to the users all the time.
## Expected Results

https://github.com/facebook/facebook-android-sdk/blob/5.x-branch/facebook-core/src/main/java/com/facebook/AccessTokenManager.java#L157

Could you please at least put alarm set to try/catch to avoid crashes in the background
```
try {
alarmManager.set(
                AlarmManager.RTC,
                accessToken.getExpires().getTime(),
                alarmIntent);
} catch (SecurityException e) {}
```
## Actual Results

```
Fatal Exception: java.lang.SecurityException
!@Too many alarms (500) registered from uid 10126
android.os.Parcel.createException (Parcel.java:1966)
android.app.AlarmManager.set (AlarmManager.java:379)
com.facebook.AccessTokenManager.setTokenExpirationBroadcastAlarm (AccessTokenManager.java:172)
com.facebook.AccessTokenManager.setCurrentAccessToken (AccessTokenManager.java:135)
com.facebook.AccessTokenManager.setCurrentAccessToken (AccessTokenManager.java:115)
com.facebook.AccessTokenManager$4.onBatchCompleted (AccessTokenManager.java:364)
com.facebook.GraphRequest$5.run (GraphRequest.java:1400)
android.os.Handler.handleCallback (Handler.java:873)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
## Steps to Reproduce

If you've set up already more than 500 alarms by the app. Some devices, especially Samsung (android 7) has some security measures to forbid to create more than 500 alarms.

Is it possible to add this try/catch code to avoid such crashes in the future?

**Comment by emreyanik** [comment]
In addition to this, could you change pending intent flag to PendingIntent.FLAG_UPDATE_CURRENT from 0 to prevent alarm duplication on some Samsung devices.

[https://github.com/facebook/facebook-android-sdk/blob/5.x-branch/facebook-core/src/main/java/com/facebook/AccessTokenManager.java#L170](https://github.com/facebook/facebook-android-sdk/blob/5.x-branch/facebook-core/src/main/java/com/facebook/AccessTokenManager.java#L170)

**Expected Result**

PendingIntent alarmIntent = PendingIntent.getBroadcast(context, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);

**Comment by vhontar** [comment]
The problem is that I have to set alarms for different local notifications for different time. So request code is different. That's why they are all different. FLAG_UPDATE_CURRENT as I understand right doesn't help in that case
```
 private fun cancelAlarm(myBookingNotification: MyBookingNotification) {
        val notificationIntent = getNotificationIntent(myBookingNotification)
        val pendingIntent = PendingIntent.getBroadcast(context, myBookingNotification.uniqueNotificationId, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT)
        val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        if (pendingIntent != null) {
            alarmManager.cancel(pendingIntent)
        }
    }
```

**Comment by emreyanik** [comment]
I think there is a misunderstanding. You're right about alarms with different request code doesn't need FLAG_UPDATE_CURRENT. But my suggestion was for facebook sdk, not for you. Because facebook set same alarm with same request code so some samsung devices throw exception when exceeds the alarm limit. Actually I increased your suggestion :)

**Comment by vhontar** [comment]
Hi, you can close the issue, thank you!

**Comment by iceteahh** [comment]
@vhontar What is the solution for it? I'm facing this problem too

**Comment by ltbaogt2** [comment]
> @vhontar What is the solution for it? I'm facing this problem too

Me too
