### ISSUE TITLE
missing maven facebook-core

### ISSUE THREAD

**Issue by JasonLinkinBright** [facebook/facebook-android-sdk#635]
Could not find com.facebook.android:facebook-core:5.11.1

**Comment by nileopen** [comment]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/12773541/69396661-fb53b080-0d1d-11ea-88a3-8aec734f98bd.png">

**Comment by nileopen** [comment]
no .aar file

**Comment by larboy1991** [comment]
Zuckerberg should let this employee fucking fire

**Comment by sejoon-mfort** [comment]
This is really shocking. I'm wondering how this could happen.

**Comment by YOUDAN** [comment]
Resolved in 5.11.2
