### ISSUE TITLE
Android build failed: Unable to find facebook-core:5.11.1

### ISSUE THREAD

**Issue by Pranav-Mtl** [facebook/facebook-android-sdk#636]
There is some issue in the new release for android 5.11.1.
Suddenly this implementation stop working
implementation 'com.facebook.android:facebook-android-sdk:[5,6)'

and I have downgraded SDK to    implementation 'com.facebook.android:facebook-android-sdk:5.8.0'
which is working fine.

Please check

**Comment by didik-maulana** [comment]
We have same problem when use 5.1.1 version, but it's normal when downgrade to 5.0.0

**Comment by YOUDAN** [comment]
Trying too resolve this issue now

**Comment by cyjkevin** [comment]
We have same problem. It must be some issue in the new release for 5.11.1

**Comment by YOUDAN** [comment]
Resolved in 5.11.2
