### ISSUE TITLE
strange log warning about event enable state

### ISSUE THREAD

**Issue by Jason-Zy** [facebook/facebook-android-sdk#639]
i enable the Auto logging app event and advertiserid collection as follow,but i find some warning about sthat, i dont know why , i have no idea whether its some thing wrong with my app.
my facebook setting page:
![image](https://user-images.githubusercontent.com/26757867/69776146-ff784600-11d5-11ea-97da-ba16671b694d.png)

warning in app:
Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events

You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.

**Comment by KylinChang** [comment]
Hi @Jason-Zy , it's just a warning message and should not affect your app. Can you check the manifest of the exported project to see whether there are those two flags?
