### ISSUE TITLE
always loading

### ISSUE THREAD

**Issue by qiangqiang681** [facebook/facebook-android-sdk#642]
i share with android sdk 5.0.1, but the sharedialog  always loading , and without any error print, 
the code is :  
```
if (ShareDialog.canShow(ShareLinkContent::class.java)) {
            val content = ShareLinkContent.Builder()
                .setContentUrl(Uri.parse(content.link))
                .setQuote(content.quote)
                .setPageId(content.postId)
                .build()
            shareDialog?.show(content)
        }
```
![Screenshot_20191210-162808](https://user-images.githubusercontent.com/19320420/70510653-479a4f80-1b6a-11ea-9581-d9dc9619fc45.jpg)

**Comment by Mxiim** [comment]
Hello,

Does it work if you update to latest release version? I have tried using latest and it worked with 
`if (shareDialog.canShow(ShareLinkContent.class)) {
     Util.ToastMessage(mFragment.getActivity(), "Dialog > CanShow = true");
}`
