### ISSUE TITLE
how to solve Unable to show the provided content via the web or the installed version of the Facebook app. Some dialogs are only supported starting API 14.

### ISSUE THREAD

**Issue by Tzthaw** [facebook/facebook-android-sdk#643]

**Comment by Mxiim** [comment]
Hello,
Have you updated to latest SDK and do you use API >= 15?
If the problem still persists -- could you give more context how you are using the SDK?

**Comment by harideepan** [comment]
Hi, I am using the latest SDK 5.15.0 and API 21. ShareDialog is not switching to the browser when the user hasn't installed a native facebook app. It not working as mentioned in the documentation.

> Built-In Share Fallbacks
> In past versions of the SDK for Android, your app had to check for a native, installed Facebook app before it could open the Share Dialog. If the person didn't have the app installed, you had to provide your own code to call a fallback dialog.
> 
> Now the SDK automatically checks for the native Facebook app. If it isn't installed, the SDK switches people to their default browser and opens the Feed Dialog.

**Comment by zongxiaomi** [comment]
how to fix this problem

**Comment by nikhiljainlive** [comment]
I am also facing the same issue. is there any fix yet?

**Comment by Mxiim** [comment]
Hi all,

I found this in the docs https://developers.facebook.com/docs/messenger-platform/changelog/#20190610 not sure if those are still supported. If you can provide me a code snipit, I can ask around.

Also, latest SDK version is 7.1.0(?)

**Comment by nikhiljainlive** [comment]
@Mxiim , thanks for the SDK version update. I upgraded it and tried the following code snippet.

```
val sharePhoto = SharePhoto.Builder()
                .setImageUrl(
                    Uri.parse("https://images.unsplash.com/photo-1494548162494-384bba4ab999?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80")
                ).setCaption("Test Photo")
                .build()
            val photoContent = SharePhotoContent.Builder()
                .addPhoto(
                    sharePhoto
                ).build()
```

**Comment by Mxiim** [comment]
Thanks, I will try to ask around since I never used the sharing part of SDK

**Comment by nikhiljainlive** [comment]
Thanks @Mxiim :) I will be looking forward to the fix of this issue.

**Comment by Mxiim** [comment]
I found some code that made it work with 
```
public static SharePhotoContent getTestPhotoContent() {
    Bitmap image =
        BitmapFactory.decodeResource(
            FacebookSdk.getApplicationContext().getResources(), R.drawable.picture);
    SharePhoto sharephoto = new SharePhoto.Builder().setBitmap(image).build();
    return new SharePhotoContent.Builder().addPhoto(sharephoto).build();
  }
```
<img width="370" alt="Screen Shot 2020-07-13 at 11 57 07 AM" src="https://user-images.githubusercontent.com/8554206/87342479-2898dd00-c500-11ea-95f5-576ee342f0d0.png">

I saw that in https://github.com/facebook/facebook-android-sdk/blob/master/facebook-common/src/main/java/com/facebook/share/widget/ShareDialog.java#L161 we check for currentAccessToken even for web, the comment says there are extra permissions needed for photo-sharing hence necessity of access token. Maybe there is no user-token when you try to share? 

Also tested with setCaption, and uri like in:
```
  public static SharePhotoContent getTestPhotoContent(Uri photoUri) {
    SharePhoto sharephoto = new SharePhoto.Builder().setImageUrl(photoUri).build();
    return new SharePhotoContent.Builder().addPhoto(sharephoto).build();
  }
```

Can you try calling and printing
```
AccessTokenManager.getInstance().getCurrentAccessToken();
```
before trying to display the dialog?
Just to make sure it is not empty. Please do NOT paste it here in the open on github. It is only important if it is empty/null or not.

If it is not empty, and I cannot easily reproduce, do you mind setting up the smallest possible MVP-app that I can reproduce by just building it locally?

**Comment by nikhiljainlive** [comment]
Thanks for the update @Mxiim . The access token is showing null before displaying the ShareDialog, does that mean I have to integrate Facebook LogIn SDK as well in case of sharing photos to Facebook Dialog?
or is there any other way I can request an access token before showing the dialog?

**Comment by Mxiim** [comment]
@nikhiljainlive Could you try posting in https://developers.facebook.com/support/bugs/ and ask about this?
I know very little about this unfortunately, I know that one ways to get access token is to be logged into facebook, I know you can also get accesstoken when using fblogin sdk. Maybe it is enough to be logged in the facebook app as well. You can try both to see if it will work

**Comment by nikhiljainlive** [comment]
Thanks @Mxiim for your overall help and I will try posting it on developers website because in the web dialog as well, we need to log in to post the content so according to me, the SDK internally should get the access token and show the dialog box but in this case, I do have to use LogIn SDK as well and this increases the complexity in the following ways for my implementation:

1.  Check manually in the code whether native app is installed or not then accordingly navigate the user to LogIn SDK flow, retrieve the token and then show the dialog.

2. If the native app is not installed, then let the Share SDK handle the implementation.

But in the first case, the LogIn SDK or OAuth seems redundant just for retrieving the access token.
Just posting this here to make the issue more relevant.

**Comment by MalcolmMcFly** [comment]
Also have the same issue, not using login, just want to use share.

**Comment by ongkecantho** [comment]
I am facing exactly the same error message when sharing Photo:

        SharePhoto photo = new SharePhoto.Builder()
                .setBitmap(image)
                .build();

        SharePhotoContent content = new SharePhotoContent.Builder()
                .addPhoto(photo)
                .setShareHashtag(new ShareHashtag.Builder()
                        .build())
                .build();

**Comment by Mxiim** [comment]
@MalcolmMcFly @ongkecantho 
Looking at implementation it looks like you would need some access token, hence using Login to have correct permissions(see my other reply in the thread).
You can ask in https://developers.facebook.com/support/bugs/ for more details if this is intended behaviour or not, since I am not familiar with this.
