### ISSUE TITLE
NullPointerException  WebLoginMethodHandler（2）

### ISSUE THREAD

**Issue by zjdyhant** [facebook/facebook-android-sdk#645]
- Android SDK Version: `5.0.0 -- 8.0.0`
- Installation Platform & Verison: `Gradle` version `5.9.0`

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.facebook.a.d()' on a null object reference
com.facebook.login.WebLoginMethodHandler.a (WebLoginMethodHandler.java:58)
com.facebook.login.WebViewLoginMethodHandler.cancel (WebViewLoginMethodHandler.java)
com.facebook.login.WebViewLoginMethodHandler$1.onComplete (WebViewLoginMethodHandler.java:4)
com.facebook.internal.WebDialog.a (WebDialog.java:12)
com.facebook.internal.WebDialog$DialogWebViewClient.shouldOverrideUrlLoading (WebDialog.java:112)
android.webkit.WebViewClient.shouldOverrideUrlLoading (WebViewClient.java:77)
xf.b (xf.java:104)
org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading (AwContentsClientBridge.java:172)
org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce (SystemMessageHandler.java)
org.chromium.base.SystemMessageHandler.handleMessage (SystemMessageHandler.java:9)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:200)
android.app.ActivityThread.main (ActivityThread.java:6956)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:836)

**Comment by Mxiim** [comment]
Hello,
Does the error persist if you update to the latest SDK version which is 5.13.0?
If not, could you show me how you reproduce the error please?

**Comment by zjdyhant** [comment]
> Hello,
> Does the error persist if you update to the latest SDK version which is 5.13.0?
> If not, could you show me how you reproduce the error please?

thanks，Our current version is 5.9.0. Several previous versions have also been appearing.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/8765604/71613917-d20f2580-2be3-11ea-9da2-006f2d080f14.png">
