### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by MiracleChen001** [facebook/facebook-android-sdk#646]
I use facebook login with my own button, it can log in success the first time.
But when I log out, and try to re-login in, it will meet this exception:

**Caught exception: javax.net.ssl.SSLPeerUnverifiedException: Hostname graph.facebook.com not verified**

SDK version :
`implementation 'com.facebook.android:facebook-android-sdk:5.12.1'` 

Does anyone meet the same issue? Is my code issue or facebook sdk's issue?

**Comment by MiracleChen001** [comment]
Sorry. It's my code issue.

**Comment by Amrutha164** [comment]
Hello, 

I'm getting the same error for latest Facebook sdk 15.2.0

Can you please let me know what you did the changes in your code..
