### ISSUE TITLE
ShareLinkContent.Builder using setPeopleIds not working on Android. It works on iOS.

### ISSUE THREAD

**Issue by andyvene** [facebook/facebook-android-sdk#650]
With the latest iOS and Android SDKs 5.x , has stopped working only 20 days ago the ShareLinkContent.Builder when using setPeopleIds ONLY for Android. Sharelink with tagging users.
It works on Android without the setPeopleIds parameter.
Instead it works great the same call for iOS.
The facebook android sdk is the v5.1.1. The same without any change , with the same fb API 5 ,was working good 20 days ago. The code remained exactly the same.
So it has to be a fb server error.

**Comment by andyvene** [comment]
Now it does not work also for iOS.  Real device. But works on IOS simulator. 
So, Facebook dev team must decide if disable this future and let the Facebook user manually tag friends , or bring it back as it was before. 

Thanks

**Comment by Mxiim** [comment]
Can you give more details how to reproduce and what error you are getting?

**Comment by andyvene** [comment]
Hello,
Well this is simple.
For iOS this is the code:

FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
		    content.contentURL =  [NSURL URLWithString:link];
		    content.peopleIDs = [[NSArray alloc] initWithObjects:usertags, nil];


		    FBSDKShareDialog *dialog = [[FBSDKShareDialog alloc] init];
		    dialog.fromViewController = nil;
		    dialog.shareContent = content;   
		    dialog.delegate = challcallbacks;

[dialog show];

The share dialog appears in the iPhone but without the fbuser that I have tagged. Ex: “ Mary is with John …”
You have to tag John manually using the iOS tag menu on the share dialog menu.
So this stopped working programmatically.

But if you tried on IOS Simulator it works.

Thanks
Andreas
