### ISSUE TITLE
Authorization error in facebook app

### ISSUE THREAD

**Issue by Thuantanon** [facebook/facebook-android-sdk#655]
I integrated the login ability according to the official website documents。But there is a error in the picture
![WechatIMG3](https://user-images.githubusercontent.com/13729873/72694899-94157980-3b71-11ea-942a-c0286f58a661.png)

**Comment by Thuantanon** [comment]
It works normally in the same signature example program，but not works in the production environment

**Comment by Mxiim** [comment]
Without seeing the code, my guess would be that you have either 1)not uploaded the correct release keyhash https://developers.facebook.com/docs/android/getting-started/#release-key-hash or 2) not using the correct keyhash to build your app in release mode. This is usually defined in your build.gradle file
