### ISSUE TITLE
Gradle build fails on 5.15.2

### ISSUE THREAD

**Issue by DouweBos** [facebook/facebook-android-sdk#673]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Kotlin Version: 1.3.61
- Installation Platform & Version: `Gradle` version `6.1.1`

```FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':reelgood:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':reelgood:releaseCompileClasspath'.
   > Could not find androidsdk.modules:shield:unspecified.
     Required by:
         project :reelgood > com.facebook.android:facebook-login:5.15.2
         project :reelgood > com.facebook.android:facebook-core:5.15.2
         project :reelgood > com.facebook.android:facebook-common:5.15.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by NicholasMiller** [comment]
I'm seeing essentially the same problem.

**Comment by romanbb** [comment]
Also seeing this exact problem.

**Comment by KylinChang** [comment]
Hi all, v5.15.3 should work.

**Comment by romanbb** [comment]
Thanks @KylinChang it does solve the issue. Will there be an official tagged release for this version?

**Comment by gitumarkk** [comment]
For react-native developers (using react-native-fbsdk) who are facing the same problem @romanbb solution can be implemented by updating the root `build.gradle` in the following location.

```
buildscript {
    ext {
        ...
        facebookSdkVersion = '5.15.3'
    }
```

**Comment by Thomazella** [comment]
@gitumarkk solution didn't work in my react-native 0.61 project. Here's the relevant fix I used in my app build.gradle
```
dependencies {
    implementation 'com.facebook.android:facebook-android-sdk:5.15.3'
}
```

**Comment by KylinChang** [comment]
Hi @romanbb , v5.15.3 is the same as v5.15.2. Close the task.
