### ISSUE TITLE
Facebook create add

### ISSUE THREAD

**Issue by mahmooooud** [facebook/facebook-android-sdk#684]
Dear Facebook Developer,
we're encountering an issue while making an app install campaign which it gives us poor daily results with about <10 installs using daily budget 1800EGP for our app that ends with (AnaMehani - انامهني) meanwhile, same budget we use it with the another app the ends with (AnaMehani - انامهني (صنايعي) ) it gives us daily estimated results from 377 - 952 app installs .. 
so we highly appreciate your support to solve this issue as soon as possible ..

Note: we've created a new app on our app dashboard and changed only the app ID into our app to test if we still face same issue with the new app or not  and it gives us satisfying results from 377 - 952 daily app installs using same budget "1800EGP" .. we hope you have a look at this issue and response to us soon ..

![Screen Shot 2020-02-11 at 3 35 13 PM](https://user-images.githubusercontent.com/27790912/74245293-6f816d00-4ceb-11ea-8fd5-aaf5a2f27c62.png)
![Screen Shot 2020-02-11 at 3 35 35 PM](https://user-images.githubusercontent.com/27790912/74245297-71e3c700-4ceb-11ea-8c81-9dd290a3feb9.png)

**Comment by Mxiim** [comment]
Hello,

If you believe this is a bug, can you submit it to https://developers.facebook.com/support/bugs/ please?
