### ISSUE TITLE
Large File warning assets/audience_network.dex

### ISSUE THREAD

**Issue by zjamshidi** [facebook/facebook-android-sdk#737]
## Environment

- Java Version: `8`
- Android SDK Version: `29`
- Installation Platform & Verison: `Gradle` version `com.google.ads.mediation:facebook:5.7.1.0`

## Goals

After I included the Facebook mediation, the app size increased and I got a warning in Google Pla console regarding a large file in assets: assets/audience_network.dex 
How can I optimize the file size?

**Comment by anas-darai** [comment]
I have the same issue with com.google.ads.mediation:facebook:5.8.0.0 .
![image](https://user-images.githubusercontent.com/51852391/80968306-4282b900-8e07-11ea-89a9-52b4a62732f6.png)

**Comment by makarenkoanton** [comment]
I have the same issue. My application increases in weight after every update of the Facebook audience. Now the dex file audio_network is 1.5 mb
<img width="991" alt="Снимок экрана 2020-05-20 в 20 05 14" src="https://user-images.githubusercontent.com/14879434/82475483-39673c80-9ad5-11ea-8195-2fe1003f77cf.png">

**Comment by quanghd96** [comment]
I have the same issue with com.facebook.android:audience-network-sdk:5.9.0

**Comment by rocboronat** [comment]
Hey Facebook guys 👋

**Comment by Nathaaaalie** [comment]
Hi, it is not warning. It's just recommendation. Unfortunately, it's not possible to use Dynamic Delivery for audience_network.dex right now.

**Comment by rocboronat** [comment]
Is it possible to use Dynamic Delivery now? 😊

**Comment by zjamshidi** [comment]
@Nathaaaalie any update?

**Comment by rocboronat** [comment]
We are still waiting for a solution 😊

**Comment by linmx0130** [comment]
Hi all! Thanks for raising this issue. However, neither Audience Network nor Facebook mediation is not maintained in this repo. Please raise the problem to [Facebook Developer Support](https://developers.facebook.com/support/) for getting help.
