### ISSUE TITLE
Google Api Error: The bundle targets unrecognized languages: fb

### ISSUE THREAD

**Issue by JuxBzh** [facebook/facebook-android-sdk#747]
After compiling my project with the SDK v6.2.0, I get an error when uploading the App Bundle indicating that my app targets an unsupported language: fb.
I looked into the res folders of the master branch and I found a folder named `values-fb-rLS`. I think it's this one that is causing the issue.
The problem had already been reported for a previous version of the SDK: https://github.com/facebook/facebook-android-sdk/issues/614

**Comment by Mxiim** [comment]
Looking at #614 last comment mentions it works on v6.3. Does it work for you?

**Comment by JuxBzh** [comment]
I must have missed this comment. I'll try and let you know the result.

**Comment by KylinChang** [comment]
Hi @Mxiim , @JuxBzh , the issue should be fixed in v6.3.0. I'll close this one. If you still have any issues, please comment under https://github.com/facebook/facebook-android-sdk/issues/614 instead.
