### ISSUE TITLE
java.lang.NullPointerException Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference

### ISSUE THREAD

**Issue by Jack6Wolf** [facebook/facebook-android-sdk#751]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Android SDK Version: Android Marshmallow,level 23
- Installation Platform & Verison: `[Maven]` version `5.8.0`

## Goals

I want you to fix this error

## Steps to Reproduce
It currently occurs in online user feedback crashes.Only device information that occurs: Android Marshmallow,level 23.Such as:itel p12,itel a11,itel a12.
The following is the stack information collected by the platform:
`
# AsyncTask #2(4074)
java.lang.NullPointerException
Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
1 android.os.Parcel.readException(Parcel.java:1605)
2 android.os.Parcel.readException(Parcel.java:1552)
3 android.app.ActivityManagerProxy.bindService(ActivityManagerNative.java:3844)
4 android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1317)
5 android.app.ContextImpl.bindService(ContextImpl.java:1286)
6 android.content.ContextWrapper.bindService(ContextWrapper.java:604)
7 com.facebook.internal.AttributionIdentifiers.com.facebook.internal.AttributionIdentifiers getAndroidIdViaService(android.content.Context)(AttributionIdentifiers.java:163)
8 com.facebook.internal.AttributionIdentifiers.com.facebook.internal.AttributionIdentifiers getAndroidId(android.content.Context)(AttributionIdentifiers.java:81)
9 com.facebook.internal.AttributionIdentifiers.com.facebook.internal.AttributionIdentifiers getAttributionIdentifiers(android.content.Context)(AttributionIdentifiers.java:180)
10 com.facebook.internal.AttributionIdentifiers.boolean isTrackingLimited(android.content.Context)(AttributionIdentifiers.java:134)
11 com.facebook.appevents.aam.MetadataIndexer$1.void run()(MetadataIndexer.java:71)
12 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
13 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
14 java.lang.Thread.run(Thread.java:818)

`

**Comment by Mxiim** [comment]
Hi, are you using latest SDK version? Also, could you please provide sample to reproduce this error?

**Comment by Jack6Wolf** [comment]
Hi,We're using the SDK version:5.8.0.We are sorry that we cannot reproduce this error at present.Because it itself comes from the log information reported by our online users' mobile phones

**Comment by KylinChang** [comment]
Hi @Jack6Wolf , the bug should be fixed in FB Android SDK v6.2.0 and above. Feel free to reopen the issue if the problem still exists.

**Comment by Jack6Wolf** [comment]
Ok, let's try to upgrade the version. Thank you for your answer.


On 4/16/2020 05:53，KylinChang<notifications@github.com> wrote：

Closed #751.
