### ISSUE TITLE
Your app is uploading users' Installed Packages information to https://graph.facebook.com without a prominent disclosure.

### ISSUE THREAD

**Issue by ankit422** [facebook/facebook-android-sdk#752]
Google Play rejected my update due to this, I'm using SDK version **5.5.1**.  Would update to the new version solve this?

Edit: I tried with the latest version and that's also got rejected.

**Comment by ankit422** [comment]
Is there any way I can fix this warning while keeping FB SDK or I have to remove it?

**Comment by KylinChang** [comment]
@ankit422, you need to make sure your privacy policy discloses how you are using the data collected by the FB SDK.

**Comment by ankit422** [comment]
@KylinChang I'm not using that data and wanted to check if there's any way I can stop this (stop FB SDK to collect this data)?

**Comment by KylinChang** [comment]
You can set the AutoLogAppEventsEnabled as false in your manifest. More details can be found here: https://developers.facebook.com/docs/app-events/gdpr-compliance/#delaying-automatic-event-collection

**Comment by ankit422** [comment]
@KylinChang I saw that but isn't it for event collection? I've received a warning from google play that 
> repeated violations can result in the suspension of this app or your Google Play Developer account
That's why I just wanted to be sure. Thanks for the help.

**Comment by sarvesh-du** [comment]
@ankit422 Do you have a fix for this?
