### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to resume activity {uomini.com.wegrok/com.facebook.FacebookActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f08008a android.app.ActivityThread.performResumeActivity

### ISSUE THREAD

**Issue by fractalbob** [facebook/facebook-android-sdk#758]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Java Version: `1.8`
- Android SDK Version: `Android10`
- Installation Platform & Version: `[Maven|Gradle|Manual]` version `3.6.3`

## Goals

What do you want to achieve?

## Expected Results

What do you expect to happen?

## Actual Results

My app crashed on one of my users' devices, a Huawei Enjoy 9s running Android 5.1. Here is the stack trace:

android.content.res.Resources.getValue (Resources.java:1266)
android.content.res.Resources.getDrawable (Resources.java:785)
android.content.res.Resources.getDrawable (Resources.java:752)
com.facebook.internal.WebDialog.createCrossImage (WebDialog.java:522)
com.facebook.internal.WebDialog.onCreate (WebDialog.java:395)
android.app.Dialog.dispatchOnCreate (Dialog.java:373)
android.app.Dialog.show (Dialog.java:274)
androidx.fragment.app.DialogFragment.onStart (DialogFragment.java:529)
androidx.fragment.app.Fragment.performStart (Fragment.java:2730)
androidx.fragment.app.FragmentStateManager.start (FragmentStateManager.java:365)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1194)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1356)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1434)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1497)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:447)
androidx.fragment.app.FragmentManager.executeOps (FragmentManager.java:2169)
androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1992)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1947)
androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1849)
androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2629)
androidx.fragment.app.FragmentManager.dispatchResume (FragmentManager.java:2589)
androidx.fragment.app.FragmentController.dispatchResume (FragmentController.java:269)
androidx.fragment.app.FragmentActivity.onResumeFragments (FragmentActivity.java:478)
androidx.fragment.app.FragmentActivity.onPostResume (FragmentActivity.java:467)
android.app.Activity.performResume (Activity.java:6088)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:2999)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3041)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2397)
android.app.ActivityThread.access$800 (ActivityThread.java:156)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1308)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5314)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:373)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:903)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:698)
## Steps to Reproduce
God only knows.
What are the steps necessary to reproduce this issue?

**Comment by mk35429** [comment]
Still gettin issue on :
 Brand: Huawei
Model: Huawei Enjoy 9s
Operating System
Version: 5.1 
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.app.debtless/com.facebook.FacebookActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080089

**Comment by fractalbob** [comment]
Hi,

Thank you for your email. Support for Facebook login was deprecated
several months ago and replaced by email login. Please install the latest
version (2.2.189) of WeGrok! Thanks.

Robert Uomini
WeGrok! Support

**Comment by thisisthekap** [comment]
@KylinChang @jingping2015 Could we reopen this one because it is still happening in production environments?

**Comment by thisisthekap** [comment]
@KylinChang @jingping2015 As this is still happening in production: Should I create a new issue, or wait for this one to be reopened?
