### ISSUE TITLE
Crash in AppLinkData class

### ISSUE THREAD

**Issue by VikaChebotar** [facebook/facebook-android-sdk#761]
## Environment

- Java Version: `1.8`
- Android SDK Version: `28`
- Installation Platform & Verison: `Gradle` version `6.3`

## Goals

What do you want to achieve?

I want the issue to be fixed in newer version of facebook-applinks SDK. I can't send PR myself because I don't know how to reproduce.

## Expected Results

What do you expect to happen?

I expect that AppLinkData.createFromAlApplinkData() won't crash, but will return null result.

## Actual Results

What actually happened? Can you provide a stack trace?

AppLinkData.createFromAlApplinkData() crashes for some links (stacktrace added in the end). It started happening after upgrading com.facebook.android:facebook-applinks to version 5.15.3 and is not fixed in the latest SDK version. 

## Steps to Reproduce

What are the steps necessary to reproduce this issue?

I can't reproduce, but we have a decent amount of crashes.

## Code Samples & Details
Relevant part of stacktrace:

```
Fatal Exception: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
       at android.net.Uri.getQueryParameter(Uri.java:1709)
       at com.facebook.applinks.AppLinkData.getAppLinkData(AppLinkData.java:447)
       at com.facebook.applinks.AppLinkData.createFromAlApplinkData(AppLinkData.java:295)

```

**Comment by KylinChang** [comment]
The issue should be fixed in v6.5.1.
