### ISSUE TITLE
Incorrect Contributing guidelines link in readme.md file

### ISSUE THREAD

**Issue by Grandolf49** [facebook/facebook-android-sdk#777]
**Issue**
The [contributing.md](https://github.com/facebook/facebook-android-sdk/tree/master/samples/FBLoginSample/CONTRIBUTING.md) link in [Contributing Guidelines](https://github.com/facebook/facebook-android-sdk/tree/master/samples/FBLoginSample#contributing) section is incorrect.

**Expected Result**
The contributing.md file should be pointing to the correct URL

**Comment by imanishbarnwal** [comment]
Hello @Grandolf49, can I take this issue?

**Comment by Grandolf49** [comment]
Hi @imanishbarnwal ! Actually, I have address this issue and the PR is also merged. I'll close this issue.

Thanks for checking out the repository!
