### ISSUE TITLE
Invalid versions of facebook-login dependency in jcenter

### ISSUE THREAD

**Issue by Amagi82** [facebook/facebook-android-sdk#783]
When viewing Android Studio's Project Structure menu, users are prompted to update to the latest version of facebook-login, but the recommended versions don't actually exist. 

```
Updates
com.facebook.android:facebook-login:7.0.0
Newer version available: 100.1.1
```
In the Dependencies tab -> facebook-login:7.0.0, under Requested Version, the top three options are 100.1.1, 100.1, and 100. 

At the time of this posting, the following all exist, empty:
https://bintray.com/bintray/jcenter/com.facebook.android%3Afacebook-login/100.1.1
https://bintray.com/bintray/jcenter/com.facebook.android%3Afacebook-login/100.1
https://bintray.com/bintray/jcenter/com.facebook.android%3Afacebook-login/100

If it's possible to remove those empty packages, they should be removed to avoid confusion among users.

**Comment by Mohammadmahdiamn** [comment]
Hi
I understand Facebook approaches, but I joined you to learn.
I will definitely help you in the future because I am interested in
technology.

Thanks Facebook team:)

>

**Comment by Mxiim** [comment]
I _think_ this has been removed since I cannot find it anymore, reopen if that is not the case.
