### ISSUE TITLE
AppEventsConstants don't have EVENT_UNLOCKED_ACHIEVEMENTS constant

### ISSUE THREAD

**Issue by gkgio** [facebook/facebook-android-sdk#794]
in https://developers.facebook.com/docs/app-events/getting-started-app-events-android#
wroted that in order to send EVENT_UNLOCKED_ACHIEVEMENTS event need use code below, but file AppEventsConstants don't contains the EVENT_UNLOCKED_ACHIEVEMENTS constant

/**
 * This function assumes logger is an instance of AppEventsLogger and has been
 * created using AppEventsLogger.newLogger() call.
 */
public void logUnlockAchievementEvent (String description) {
    Bundle params = new Bundle();
    params.putString(AppEventsConstants.EVENT_PARAM_DESCRIPTION, description);
    logger.logEvent(AppEventsConstants.EVENT_UNLOCKED_ACHIEVEMENTS, params);
}

**Comment by Mxiim** [comment]
Hi, I think it is just called `EVENT_NAME_UNLOCKED_ACHIEVEMENT` in https://github.com/facebook/facebook-android-sdk/blob/master/facebook-core/src/main/java/com/facebook/appevents/AppEventsConstants.java#L99

Let me know if that does not work
