### ISSUE TITLE
Facebook SDK will query facebook provider regardless of whether `FacebookSdk.setAutoInitEnabled(false)` is set

### ISSUE THREAD

**Issue by jxdabc** [facebook/facebook-android-sdk#812]
version: 
Facebook SDK 5.1.1 for Android

issue:
Facebook SDK will query facebook provider regardless of whether `FacebookSdk.setAutoInitEnabled(false)` is set.
This behavior will be recorded by some manufacturer Android OS, as attached, and cause user confuzed.

expected behavior:
Facebook SDK won't query facebook provider on `FacebookSdk.setAutoInitEnabled(false)` set.

![screenshot_0_1595816510374-TudlBGyELY (2)](https://user-images.githubusercontent.com/2919303/88755084-de1b8f80-d192-11ea-932b-1fc24478e8eb.jpg)

**Comment by agGitHub** [comment]
Put in manifest:

```
        <meta-data
            android:name="com.facebook.sdk.AutoInitEnabled"
            android:value="false" />
```
