### ISSUE TITLE
FBLoginSample multi facebook account

### ISSUE THREAD

**Issue by TechComet** [facebook/facebook-android-sdk#813]
Hi,

FBLoginSample

I login to my facebook account ..
I logout
how reauth to two facebook account?

**Comment by TechComet** [comment]
issue not fixed

**Comment by Mxiim** [comment]
Can you re-open the issue with more info what you expect to happen and how?

**Comment by iamen12345** [comment]
dura esta weiiiiestamos enterados con los marci anos lownson haward reproductor sopilote metiche ala motfestera rexuperamos el angulo streaming

- [ ] 

> lowmenshot
