### ISSUE TITLE
Get signed_request 

### ISSUE THREAD

**Issue by lunicleonid** [facebook/facebook-android-sdk#814]
https://github.com/facebook/facebook-android-sdk/blob/master/facebook-common/src/main/java/com/facebook/CustomTabActivity.java#L49

How can I get the "signed_request"? For the situation when the backend can't be changed (long story...), and the "sign in with facebook" is implemented only for "web" and not for mobile. 
My solution was to make a clone of the facebook-common module, but ideally I would like to be able to get the signed request  from the original facebook sdk.

Thank you.

**Comment by alexminza** [comment]
@lunicleonid I think a PR would be much more helpful here and easier to understand the issue you are encountering.

**Comment by brunomanoel2019** [comment]
Hey guy, 
i can resovler this problem !

**Comment by Uwdieyn-Network-Team** [comment]
https://github.com/facebook/facebook-android-sdk/blob/2aac18fd5f42c23b06a3bb13e1be0577be93da76/facebook-common/src/main/java/com/facebook/CustomTabActivity.java
