### ISSUE TITLE
Can't login with 8.0.0 without fb client app installed

### ISSUE THREAD

**Issue by Artemych** [facebook/facebook-android-sdk#833]
## Goals

Log in with fb sdk

## Expected Results

Login successful.

## Actual Results

web page with the text:

Sorry, something went wrong.
We are working on it and we'll get it fixed as soon as we can.

## Steps to Reproduce

There is no fb client app on the device. Then I tried to login with 

```kotlin
LoginManager.getInstance().logInWithReadPermissions(activity, Arrays.asList("email", "user_birthday"))
```
Then i grant read permissions to the app and then got the error.

Everything works fine with 5.13.0 but i get this error on 8.0.0 sdk. Also everything works for me with 8.0.0 if i have fb client app installed.

## Code Samples & Details

```kotlin
val fbCallbackManager = CallbackManager.Factory.create()
LoginManager.getInstance().registerCallback(fbCallbackManager, object : FacebookCallback<LoginResult> {
        override fun onSuccess(loginResult: LoginResult) {
            //app code here
        }

       override fun onCancel() {
            //app code here
       }

       override fun onError(e: FacebookException) {
            //app code here
        }
})
LoginManager.getInstance().logInWithReadPermissions(activity, Arrays.asList("email", "user_birthday"))
```

**Comment by Mxiim** [comment]
Hello,
Are you targetting API level 30 btw? Will take a look at this :)

**Comment by Mxiim** [comment]
I tried reproduce this with same permissions, and it does work. Could you submit a more detailed report on https://developers.facebook.com/support/bugs/ ?

**Comment by Artemych** [comment]
> Hello,
> Are you targetting API level 30 btw? Will take a look at this :)

no my target is 29

**Comment by Artemych** [comment]
> I tried reproduce this with same permissions, and it does work. Could you submit a more detailed report on https://developers.facebook.com/support/bugs/ ?

sure will do
