### ISSUE TITLE
Can't Login on Android 11 API 30

### ISSUE THREAD

**Issue by skauss** [facebook/facebook-android-sdk#836]
Hi,
today I update the Facebook SDK from 
- implementation 'com.facebook.android:facebook-android-sdk:[5,6]'
to
- implementation 'com.facebook.android:facebook-android-sdk:8.0.0'

For this reason I test our code which call the GraphAPI on different devices.
Our code work on Android devices like

- Nexus 5x with Android 8.1
- Huawei ANE-LX1 with Android 8.0.0
- Samsung S8 with Android 9
- **but not** on Pixel 4a with **Android 11**

for this reason I suppose a problem in the Facebook SDK at Android 11.

Hint ; it is **not a new problem** with Facebook SDK 8.0.0 the problem also exist in Facebook SDK 6.x.x

In case I call the GraphAPI (GraphRequest) first I do an login 
with LoginManager.getInstance().registerCallback(...)

I get the login screen picture 

![device-2020-10-01-144338_FacebookLogin_1](https://user-images.githubusercontent.com/2562792/94811895-42a6d500-03f6-11eb-8927-70207dbe63ea.png)

but if I touch the screen before a keyboard is shown I get screen picture

![device-2020-10-01-144338_FacebookLogin_2](https://user-images.githubusercontent.com/2562792/94811901-463a5c00-03f6-11eb-867f-7dfa47cccd6f.png)

which send me to an external browser outside my app.

Regards
Stephan

**Comment by Mxiim** [comment]
Hello!
I _think_ it could be because of https://developer.android.com/about/versions/11/privacy/package-visibility in Android 11, could you try adding `com.facebook.katana` to the queries elements as per https://developer.android.com/training/basics/intents/package-visibility#package-name ?

**Comment by skauss** [comment]
Hi Mxiim,
I try to add this into my AndroidManifest.xml file 
`    <queries>
            <package android:name="com.facebook.katana" />
        </queries>
`
And end up in the gradle build tool hell.

With gradle-wrapper.properties 
`
    distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
`
and build.gradle 
`
  classpath 'com.android.tools.build:gradle:4.0.1'
`
the Build failed with 

`
app/src/main/AndroidManifest.xml:274:9-277:19: AAPT: error: unexpected element <queries> found in <manifest><application>.
`
The documentation at 
https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html
Say build tools gradle 4.0.1 must be fine, but didn't.

With classpath 'com.android.tools.build:gradle:4.1.0-beta05' 
I need distributionUrl=https\://services.gradle.org/distributions/gradle-6.6.1-all.zip
which end up in the Android Studio Error 
`
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.1 or newer.
`
For the moment I have no idea how to get further with this problem.
Any idea ?
Regards

**Comment by skauss** [comment]
Thanks for your hint.

My main mistake was to add the queries inside the application part.
It must be between manifest and   application
