### ISSUE TITLE
Update target29, crash on Android 10

### ISSUE THREAD

**Issue by younger96** [facebook/facebook-android-sdk#842]
# Environment
- Java Version: `1.8.0`
- Android SDK Version: `29.0.0`
- Installation Platform & Verison: `[Maven|Gradle|Manual]` version `5.8.0`

Hi~My Facebook SDK version is  5.8.0 and I update my Android SDK to target29,there are lib.so crash on my android 10 device.
My previous Facebook SDK is 4.x.x is no such crash, please tell me how can I fix it?   Thank you ~!

backtrace:
  #00  pc 000000000005f296  /apex/com.android.runtime/lib/bionic/libc.so (abort+166)
  #00  pc 0000000000377569  /apex/com.android.runtime/lib/libart.so (art::Runtime::Abort(char const*)+1676)
  #00  pc 000000000000855f  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+406)
  #00  pc 0000000000325623  /apex/com.android.runtime/lib/libart.so (art::OatHeader::GetCompilerFilter() const+170)
  #00  pc 000000000032afbd  /apex/com.android.runtime/lib/libart.so (art::OatFile::GetCompilerFilter() const+20)
  #00  pc 000000000033336f  /apex/com.android.runtime/lib/libart.so (art::OatFileManager::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+242)
  #00  pc 00000000003813b5  /apex/com.android.runtime/lib/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+68)
  #00  pc 000000000038fd65  /apex/com.android.runtime/lib/libart.so (art::SignalCatcher::HandleSigQuit()+1036)
  #00  pc 000000000038f1cf  /apex/com.android.runtime/lib/libart.so (art::SignalCatcher::Run(void*)+242)
  #00  pc 00000000000a6133  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #00  pc 0000000000060743  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

![image](https://user-images.githubusercontent.com/18147660/95938979-a628fd80-0e0d-11eb-96c8-1779912247b7.png)

![image](https://user-images.githubusercontent.com/18147660/95938993-ae813880-0e0d-11eb-80f5-eb9d52a90360.png)

**Comment by Mxiim** [comment]
It does not seem like anything in the stacktrace suggests it is caused by the facebook sdk. Also the latest major version for the sdk is 8

**Comment by nitinjain12** [comment]
Is there any workaround for this crash?

**Comment by younger96** [comment]
> Is there any workaround for this crash?

No～Do you have the same crash? If you have solution , please tell me . Thanks

**Comment by nitinjain12** [comment]
yes we do have the same crash. we have upgraded the FAN SDK to 6.2.0. but still getting the crash

**Comment by maukur** [comment]
Same problem

**Comment by reachzhai** [comment]
Same problem

**Comment by WCK02** [comment]
we do have the same crash. we have upgraded the FAN SDK to 6.3.0. but still getting the crash
