### ISSUE TITLE
Request: make it clear whether Facebook Places is going to be removed or not

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [facebook/facebook-android-sdk#856]
For some reason I see that it's removed here:
https://developers.facebook.com/docs/places/web/search

But finding this, I don't see it mentioned:
https://developers.facebook.com/docs/places/android/
https://github.com/facebook/facebook-android-sdk/tree/master/samples/PlacesGraphSample?fbclid=IwAR1nizof_OVx4k7AR8zBJwgZPpBnjTZZPW9DiBqu7bRBv-DeW8PUzLVWj8U

Is it possible that for Android, it won't be removed, but for the web it will?
What is going on?

Also, in some old project I need to work on, I can see that I can reach PlaceSearchRequestParams class for example, but I don't see `com.facebook.android:facebook-places` being used in gradle file.  Is it possible something else contains it too?

**Comment by Mxiim** [comment]
Hello,

It will be removed, I think it was marked for deprecation in V6 or V7. Can not fully remove directly as some internal projects depend on it as well. 
It is already "removed" on gradle since we do not release it to maven anymore

**Comment by AndroidDeveloperLB** [comment]
@Mxiim I've also seen these:

https://developers.facebook.com/docs/places/overview
https://developers.facebook.com/docs/places/android
https://developers.facebook.com/docs/places/android/information

And I don't see it says those will be removed.

What I think is that for the web it was removed, but not for Android. Could it be?

**Comment by jawwad** [comment]
Hi @AndroidDeveloperLB,

I've worked with @Mxiim to remove references to the Places SDK from the README and have also added deprecation messages to the pages you've mentioned. I will also look into removing references to those pages from the documentation completely. If you come across any other references to the Places SDK that don't show a deprecation message please let me know. Thanks for reporting this!

**Comment by AndroidDeveloperLB** [comment]
@jawwad Please write in each that it's not just deprecated, but won't work anymore and will be removed.
I've spent some time to see that it's actually not going to work anymore...

**Comment by jawwad** [comment]
@AndroidDeveloperLB - That's a good point. I've updated the wording to be a bit stronger and say that the Places SDK has been removed (vs deprecated). The note already indicated that it would not work as of Graph API 6.0. (Technically the source code for the SDK is still available for now due to the technical limitations @Mxiim mentioned but it is essentially removed since there were no additional releases to maven since v7.1.0).

**Comment by AndroidDeveloperLB** [comment]
@jawwad Please write it here too, as the first sentence, with red color for "warning" .

**Comment by jawwad** [comment]
@AndroidDeveloperLB - Thanks for catching that! I've gone ahead and removed the PlacesGraphSample sample project in 03b099f.

**Comment by AndroidDeveloperLB** [comment]
@jawwad Thank you.
Do you know perhaps why this entire API was removed? Is there an alternative for it from Facebook?
What are the alternatives from other companies? I know only of Google Places API, but it costs money compared to Facebook which was for free (as far as I remember).

**Comment by jawwad** [comment]
@AndroidDeveloperLB  - I know it was deprecated because the Graph API endpoint was deprecated but I don't know why the endpoint itself was deprecated. (I searched a bit but didn't find any info on this). I know there isn't an alternative from Facebook. Sorry that I couldn't be of more help on this.

**Comment by AndroidDeveloperLB** [comment]
@jawwad Wait, how can you manage this repository, if you aren't from Facebook company?  Or are you?

**Comment by jawwad** [comment]
Hi @AndroidDeveloperLB,

I know that it's frustrating that this was deprecated without much of an explanation or a replacement for it. Endpoints can be deprecated for a variety of reasons ranging from low usage to abuse potential. I also don't know of a good alternative. You mentioned that there is the Google Places API but it isn't free. I did find this article that lists a few alternatives to the Google Places API: https://traveltime.com/blog/google-places-api-alternatives-points-of-interest-data. Sorry that there isn't an alternative available from Facebook.

**Comment by AndroidDeveloperLB** [comment]
@jawwad It seems that instead of having more and more competition between services, there is actually less and less.
Each time it's weird for me to see big companies like Facebook and Google ditch services. Here it's Facebook places API, and Google does it all the time, including even for users with its Google Photos not being unlimited anymore (despite their promises)...
I remember Facebook itself had plenty of APIs for details of a user's friends and similar stuff (with approval of the current user, of course). Nowadays, it's closing more and more APIs. 

Anyway, nice to see you've found this link.
Thank you.
