### ISSUE TITLE
Should I login with Facebook in Webview?

### ISSUE THREAD

**Issue by theabbie** [facebook/facebook-android-sdk#859]
Some Apps that have implemented login with Facebook often ask you to login to Facebook in a Webview window.   

When using the autofill to fill credentials, it asks whether you trust the app. As far as I know, the app can easily steal login details from the Webview, is it safe to login in such cases, or, is it a violation? Should we report such apps to Facebook?  

One such app would be PubG, which used Webview login. There are better methods to login with Facebook by opening a chrome window, which is much safer and convenient.  The Webview login should be discontinued.

**Comment by theabbie** [comment]
Example, 9gag

![Screenshot_20201111-003041_9GAG](https://user-images.githubusercontent.com/17960677/98719683-1186d080-23b6-11eb-8105-40e9288fd471.png)
![Screenshot_20201111-003147_Google_Play_services](https://user-images.githubusercontent.com/17960677/98719686-13509400-23b6-11eb-8c7b-0b258bc3fc21.png)

**Comment by theabbie** [comment]
@yns88

**Comment by dustin268** [comment]
I lost my password to my page and I don't have the same number, so how can I get my page back, thank you

**Comment by jingping2015** [comment]
Login through Webview has been deprecated, please check :  https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews
