### ISSUE TITLE
com.facebook.android:facebook-android-sdk:8.1.0  bug

### ISSUE THREAD

**Issue by 317056658** [facebook/facebook-android-sdk#871]
Lack of fB_mobile_complete_registration of currency and value parameters excuse me how to resolve, affect buried point? 
I did not find the documents of 8.1. The others are old documents that cannot solve my problem. Do you have the documents of 8.1 for reference?
![lALPDhYBONUefrTNAl3NBA0_1037_605](https://user-images.githubusercontent.com/24821879/100361783-8f451000-3035-11eb-94fd-28c89e40e386.png)

**Comment by Hacker-s-wife** [comment]
require​ ​'facebook-php-sdk/src/facebook.php'​; 

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();

**Comment by Hacker-s-wife** [comment]
require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();require​ ​'facebook-php-sdk/src/facebook.php'​;

​$​facebook​ = ​new​ ​Facebook​(​array​(
  ​'appId'​  => ​'YOUR_APP_ID'​,
  ​'secret'​ => ​'YOUR_APP_SECRET'​,
));

​// Get User ID​
​$​user​ = ​$​facebook​->​getUser​();
