### ISSUE TITLE
Use ActivityResultContracts as onActivityResult is deprecated

### ISSUE THREAD

**Issue by VincentJoshuaET** [facebook/facebook-android-sdk#875]
```
/**
     * Receive the result from a previous call to
     * {@link #startActivityForResult(Intent, int)}.  This follows the
     * related Activity API as described there in
     * {@link Activity#onActivityResult(int, int, Intent)}.
     *
     * @param requestCode The integer request code originally supplied to
     *                    startActivityForResult(), allowing you to identify who this
     *                    result came from.
     * @param resultCode The integer result code returned by the child activity
     *                   through its setResult().
     * @param data An Intent, which can return result data to the caller
     *               (various data can be attached to Intent "extras").
     *
     * @deprecated use
     * {@link #registerForActivityResult(ActivityResultContract, ActivityResultCallback)}
     * with the appropriate {@link ActivityResultContract} and handling the result in the
     * {@link ActivityResultCallback#onActivityResult(Object) callback}.
     */
    @SuppressWarnings("DeprecatedIsStillUsed")
    @Deprecated
    public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        if (FragmentManager.isLoggingEnabled(Log.VERBOSE)) {
            Log.v(FragmentManager.TAG, "Fragment " + this + " received the following in "
                    + "onActivityResult(): requestCode: " + requestCode + " resultCode: "
                    + resultCode + " data: " + data);
        }
    }
```

**Comment by Akshit6828** [comment]
Hi @VincentJoshuaET  can i work on this issue?

**Comment by sergpetrov** [comment]
Hi! Any progress on this enhancement?

**Comment by Akshit6828** [comment]
So sorry! Actually, I got this message just now.  Just give me 1-2 days, I'll fix it.

**Comment by willc0de4food** [comment]
> 
> 
> Hi! Any progress on this enhancement?

I am also wondering about this :)

**Comment by Akshit6828** [comment]
Hi @sergpetrov and @willc0de4food. 
Actually, I have one doubt! 
Please if you could help me as I am beginner to Contribute to such big projects.

I am searching for  `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.

**Also Please correct me if I am wrong in finding the way.**

As when I search the result in the results are somewhere like this : 

![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)

Please if could link me to the Line of Code where I need to change the code as done [here][change]


[change]:https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173

**Comment by Akshit6828** [comment]
> Hi @sergpetrov and @willc0de4food.
> Actually, I have one doubt!
> Please if you could help me as I am beginner to Contribute to such big projects.
> 
> I am searching for `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.
> 
> **Also Please correct me if I am wrong in finding the way.**
> 
> As when I search the result in the results are somewhere like this :
> 
> ![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)
> 
> Please if could link me to the Line of Code where I need to change the code as done [here](https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173)

## The deprecated method can be updated as shown below:

```

 public void openSomeActivityForResult() {
        Intent intent = new Intent(this, SomeActivity.class);
        someActivityResultLauncher.launch(intent);
    }


ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(
            new ActivityResultContracts.StartActivityForResult(),
            new ActivityResultCallback<ActivityResult>() {
                @Override
                public void onActivityResult(ActivityResult result) {
                    if (result.getResultCode() == Activity.RESULT_OK) {
                        // There are no request codes
                        Intent data = result.getData();
                        doSomeOperations();
                    }
                }
            });

   
```

**Comment by hackstarsj** [comment]
> > Hi @sergpetrov and @willc0de4food. I am sorry for the delay 😢
> > Actually, I have one doubt!
> > Please if you could help me as I am beginner to Contribute to such big projects.
> > I am searching for `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.
> > **Also Please correct me if I am wrong in finding the way.**
> > As when I search the result in the results are somewhere like this :
> > ![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)
> > Please if could link me to the Line of Code where I need to change the code as done [here](https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173)
> 
> ## The deprecated method can be updated as shown below:
> ```
> 
>  public void openSomeActivityForResult() {
>         Intent intent = new Intent(this, SomeActivity.class);
>         someActivityResultLauncher.launch(intent);
>     }
> 
> 
> ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(
>             new ActivityResultContracts.StartActivityForResult(),
>             new ActivityResultCallback<ActivityResult>() {
>                 @Override
>                 public void onActivityResult(ActivityResult result) {
>                     if (result.getResultCode() == Activity.RESULT_OK) {
>                         // There are no request codes
>                         Intent data = result.getData();
>                         doSomeOperations();
>                     }
>                 }
>             });
> 
>    
> ```

You just copy paste the stackoverflow answer and it will not work for Facebook login

**Comment by Akshit6828** [comment]
> > > Hi @sergpetrov and @willc0de4food. I am sorry for the delay 😢
> > > Actually, I have one doubt!
> > > Please if you could help me as I am beginner to Contribute to such big projects.
> > > I am searching for `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.
> > > **Also Please correct me if I am wrong in finding the way.**
> > > As when I search the result in the results are somewhere like this :
> > > ![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)
> > > Please if could link me to the Line of Code where I need to change the code as done [here](https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173)
> > 
> > 
> > ## The deprecated method can be updated as shown below:
> > ```
> > 
> >  public void openSomeActivityForResult() {
> >         Intent intent = new Intent(this, SomeActivity.class);
> >         someActivityResultLauncher.launch(intent);
> >     }
> > 
> > 
> > ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(
> >             new ActivityResultContracts.StartActivityForResult(),
> >             new ActivityResultCallback<ActivityResult>() {
> >                 @Override
> >                 public void onActivityResult(ActivityResult result) {
> >                     if (result.getResultCode() == Activity.RESULT_OK) {
> >                         // There are no request codes
> >                         Intent data = result.getData();
> >                         doSomeOperations();
> >                     }
> >                 }
> >             });
> > 
> >    
> > ```
> 
> You just copy paste the stackoverflow answer and it will not work for Facebook login

Yes, sir @hackstarsj. I Just mentioned an example of how the issue could be solved using the `ActivityResultContracts`. 
It would be nice of you if you help me clearing the above-explained doubt.

**Comment by hackstarsj** [comment]
> > > > Hi @sergpetrov and @willc0de4food. I am sorry for the delay 😢
> > > > Actually, I have one doubt!
> > > > Please if you could help me as I am beginner to Contribute to such big projects.
> > > > I am searching for `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.
> > > > **Also Please correct me if I am wrong in finding the way.**
> > > > As when I search the result in the results are somewhere like this :
> > > > ![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)
> > > > Please if could link me to the Line of Code where I need to change the code as done [here](https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173)
> > > 
> > > 
> > > ## The deprecated method can be updated as shown below:
> > > ```
> > > 
> > >  public void openSomeActivityForResult() {
> > >         Intent intent = new Intent(this, SomeActivity.class);
> > >         someActivityResultLauncher.launch(intent);
> > >     }
> > > 
> > > 
> > > ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(
> > >             new ActivityResultContracts.StartActivityForResult(),
> > >             new ActivityResultCallback<ActivityResult>() {
> > >                 @Override
> > >                 public void onActivityResult(ActivityResult result) {
> > >                     if (result.getResultCode() == Activity.RESULT_OK) {
> > >                         // There are no request codes
> > >                         Intent data = result.getData();
> > >                         doSomeOperations();
> > >                     }
> > >                 }
> > >             });
> > > 
> > >    
> > > ```
> > 
> > 
> > You just copy paste the stackoverflow answer and it will not work for Facebook login
> 
> Yes, sir @hackstarsj. I Just mentioned an example of how the issue could be solved using the `ActivityResultContracts`.
> It would be nice of you if you help me clearing the above-explained doubt.

We all are waiting for new sdk release till then i just remove the Facebook login from my app..

Because if you add deprecated code on activity result google play reject the update

**Comment by sbwhy** [comment]
别烦了 why sb ***@***.*** 签名由 网易邮箱大师 定制 On 06/04/2021 18:09, SuperCoders wrote: Hi @sergpetrov and @willc0de4food. I am sorry for the delay 😢 Actually, I have one doubt! Please if you could help me as I am beginner to Contribute to such big projects. I am searching for onActivityResult(int request code... and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used. Also Please correct me if I am wrong in finding the way. As when I search the result in the results are somewhere like this : Please if could link me to the Line of Code where I need to change the code as done here The deprecated method can be updated as shown below: 

 public void openSomeActivityForResult() {

        Intent intent = new Intent(this, SomeActivity.class);

        someActivityResultLauncher.launch(intent);

    }





ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(

            new ActivityResultContracts.StartActivityForResult(),

            new ActivityResultCallback<ActivityResult>() {

                @Override

                public void onActivityResult(ActivityResult result) {

                    if (result.getResultCode() == Activity.RESULT_OK) {

                        // There are no request codes

                        Intent data = result.getData();

                        doSomeOperations();

                    }

                }

            });



   

 You just copy paste the stackoverflow answer and it will not work for Facebook login Yes, sir @hackstarsj. I Just mentioned an example of how the issue could be solved using the ActivityResultContracts. It would be nice of you if you help me clearing the above-explained doubt. We all are waiting for new sdk release till then i just remove the Facebook login from my app.. Because if you add deprecated code on activity result google play reject the update — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ArcherEmiya05** [comment]
> 
> 
> > > > > Hi @sergpetrov and @willc0de4food. I am sorry for the delay 😢
> > > > > Actually, I have one doubt!
> > > > > Please if you could help me as I am beginner to Contribute to such big projects.
> > > > > I am searching for `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.
> > > > > **Also Please correct me if I am wrong in finding the way.**
> > > > > As when I search the result in the results are somewhere like this :
> > > > > ![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)
> > > > > Please if could link me to the Line of Code where I need to change the code as done [here](https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173)
> > > > 
> > > > 
> > > > ## The deprecated method can be updated as shown below:
> > > > ```
> > > > 
> > > >  public void openSomeActivityForResult() {
> > > >         Intent intent = new Intent(this, SomeActivity.class);
> > > >         someActivityResultLauncher.launch(intent);
> > > >     }
> > > > 
> > > > 
> > > > ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(
> > > >             new ActivityResultContracts.StartActivityForResult(),
> > > >             new ActivityResultCallback<ActivityResult>() {
> > > >                 @Override
> > > >                 public void onActivityResult(ActivityResult result) {
> > > >                     if (result.getResultCode() == Activity.RESULT_OK) {
> > > >                         // There are no request codes
> > > >                         Intent data = result.getData();
> > > >                         doSomeOperations();
> > > >                     }
> > > >                 }
> > > >             });
> > > > 
> > > >    
> > > > ```
> > > 
> > > 
> > > You just copy paste the stackoverflow answer and it will not work for Facebook login
> > 
> > 
> > Yes, sir @hackstarsj. I Just mentioned an example of how the issue could be solved using the `ActivityResultContracts`.
> > It would be nice of you if you help me clearing the above-explained doubt.
> 
> We all are waiting for new sdk release till then i just remove the Facebook login from my app..
> 
> Because if you add deprecated code on activity result google play reject the update

Google PlayStore never rejects an app with deprecated code, only those app that still uses old openssl library got a problem.

**Comment by mayuce** [comment]
So, any update after all for this issue? We can't just skip by using deprecated function as a solution.

**Comment by bishiboosh** [comment]
I think I may have the time to try a solution for this, I have this problem too and I think I see what can be done

**Comment by bishiboosh** [comment]
After looking at the code, scope may be a bit big, so I may not be able to look into it right now, but I'll try at soon as I can (or if someone has the time I can share what I've found so far)

**Comment by rohit19img** [comment]
> > > > > > Hi @sergpetrov and @willc0de4food. I am sorry for the delay 😢
> > > > > > Actually, I have one doubt!
> > > > > > Please if you could help me as I am beginner to Contribute to such big projects.
> > > > > > I am searching for `onActivityResult(int request code...` and I am a little confused as I am not able to figure the exact file where I have to change the method as it is showing me these many results where this method is being used.
> > > > > > **Also Please correct me if I am wrong in finding the way.**
> > > > > > As when I search the result in the results are somewhere like this :
> > > > > > ![image](https://user-images.githubusercontent.com/57808363/120567389-467c7280-c42f-11eb-9794-6bc752ff0edf.png)
> > > > > > Please if could link me to the Line of Code where I need to change the code as done [here](https://github.com/Akshit6828/facebook-android-sdk/blob/06d46303b0f3cdfba077a2429e617ebfef6389bf/samples/RPSSample/src/com/example/rps/MainActivity.java#L173)
> > > > > 
> > > > > 
> > > > > ## The deprecated method can be updated as shown below:
> > > > > ```
> > > > > 
> > > > >  public void openSomeActivityForResult() {
> > > > >         Intent intent = new Intent(this, SomeActivity.class);
> > > > >         someActivityResultLauncher.launch(intent);
> > > > >     }
> > > > > 
> > > > > 
> > > > > ActivityResultLauncher<Intent> someActivityResultLauncher = registerForActivityResult(
> > > > >             new ActivityResultContracts.StartActivityForResult(),
> > > > >             new ActivityResultCallback<ActivityResult>() {
> > > > >                 @Override
> > > > >                 public void onActivityResult(ActivityResult result) {
> > > > >                     if (result.getResultCode() == Activity.RESULT_OK) {
> > > > >                         // There are no request codes
> > > > >                         Intent data = result.getData();
> > > > >                         doSomeOperations();
> > > > >                     }
> > > > >                 }
> > > > >             });
> > > > > 
> > > > >    
> > > > > ```
> > > > 
> > > > 
> > > > You just copy paste the stackoverflow answer and it will not work for Facebook login
> > > 
> > > 
> > > Yes, sir @hackstarsj. I Just mentioned an example of how the issue could be solved using the `ActivityResultContracts`.
> > > It would be nice of you if you help me clearing the above-explained doubt.
> > 
> > 
> > We all are waiting for new sdk release till then i just remove the Facebook login from my app..
> > Because if you add deprecated code on activity result google play reject the update
> 
> Google PlayStore never rejects an app with deprecated code, only those app that still uses old openssl library got a problem.

Google play store rejects app on this issue, my app got rejected twice for the same issue.
they asked me to remove onActivityResult method.

**Comment by marlonbosse** [comment]
Any progress on this?

**Comment by renanboni** [comment]
This PR was opened in December last year and still no updates? I'm blocked because I started a project with Jetpack compose and I can't use these legacy codes because they don't support it anymore.

**Comment by Berki2021** [comment]
This is really a shame for Facebook, as this update ULTIMATELY BLOCKS ANY USAGE OF FACEBOOK LOGIN inside Android. My app is not released yet, but if Facebook does not fix this issue, I will just throw the facebook-login out of my app and change it with something else

**Comment by linmx0130** [comment]
Hi all. Thank you for the discussion on this issue. We did receive the pull request https://github.com/facebook/facebook-android-sdk/pull/969 and we're working on figuring out a good solution which has minimal costs to migrate. Now we're now testing the solution and we will release the new APIs to avoid using `onActivityResult` in v12.0 release (in early October).

**Comment by linmx0130** [comment]
All the functions are completed in f0b7bc66beec4407144af690a8983bcc1086dc3c. We will soon release v12.0 to Maven! Thank you again for using Facebook Android SDK!

**Comment by ominfowave** [comment]
@Jeff11 Hi, can you explain what changes are required apart from removing onActivityResult method? I checked posts from linmx0130 but couldn't figure it out.

**Comment by Berki2021** [comment]
> 
> 
> @ominfowave I used this way to implement without onActivityResult for CallbackManager: The deprecated FB login method which needs to adopt onActivityResult: `LoginManager.getInstance().logInWithReadPermissions(Fragment.this, Arrays.asList("public_profile", "email"));` The new approach is adding callbackManager as the second parameter. This way is no need to add onActivityResult for callbackManager: `LoginManager.getInstance().logInWithReadPermissions(Fragment.this, callbackManager, Arrays.asList("public_profile", "email"));`

THANK YOU VERY MUCH!

**Comment by ArcherEmiya05** [comment]
> All the functions are completed in [f0b7bc6](https://github.com/facebook/facebook-android-sdk/commit/f0b7bc66beec4407144af690a8983bcc1086dc3c). We will soon release v12.0 to Maven! Thank you again for using Facebook Android SDK!

Tried removing this based on what the documentation says
```
 //TODO wait for the SDK update
    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {

        if (resultCode == Activity.RESULT_OK)
            showProgress(true);

        //Pass the activity result back to the Facebook SDK
        mCallbackManager.onActivityResult(requestCode, resultCode, data);

        super.onActivityResult(requestCode, resultCode, data);

    }
```

But after logging in nothing happens, in what part of this new version we can get the callback of a success login?

![image](https://user-images.githubusercontent.com/38008900/139886109-b9056a4f-f34d-4d27-ade5-80fa01a923ae.png)

The documentation does not help either, `onActivityResult` is triggered when a success sign in was done. Now that it is no longer needed when using AndroidX like AppCompatActivity then where can we get it?

**Comment by mazhigbee-pb** [comment]
This should really be included in the documentation next steps, it took me a long time to find this thread.

**Comment by yehia2030** [comment]
it doesn't work with activities it just works with fragments could you provide us with a solution ?

**Comment by avdovichev** [comment]
Real work regarding to this issue was done in b48ac0d1339e198cc9d8f5e8b815da4363c6f7b0

From what I see in code and what I have on results of testing is that there is an issue with current implementation.
Implementation does not follow recommendation to "decouple the result callback from the place in your code where you launch the other activity" ( https://developer.android.com/training/basics/intents/result ).

Problem occurs when activity that calls LoginManager::logInWithReadPermissions, that's it, activityResultRegistryOwner, gets destroyed (application was put to background while Facebook login form is active, for example).
When activity destroyed, launcher will be unregistered and when activity is created again, launcher is never registered again and activity will not get its FacebookCallback invoked.

I'm talking about LoginManager::startActivityForResult function.

Launcher should be instantiated and registered with registerForActivityResult function of ComponentActivity. Probably LoginManager::registerCallback is a good place to register the launcher. 

From documentation: "You must call registerForActivityResult() before the fragment or activity is created". This description is unclear about calling registerForActivityResult from onCreate.

Please note, that you should use same launcher instance that is created with registerForActivityResult to launch login intent.

Steps to reproduce the problem:
1. Turn on "Don't keep activities" option in device setting to make problem reproducing easier
2. Try to sign in using LoginManager::logInWithReadPermissions
3. Make sure calling activity is destroyed (put something to Logcat)
4. See that neither FacebookCallback instance nor launcher callback from LoginManager called after completing login form
5. Nothing happens - application remains in logged out state after returning from Facebook login form

**Comment by EmilAlipiev** [comment]
Ultimate solution is to remove facebook from all apps. Such shame for facebook always makes developers life harder.
