### ISSUE TITLE
Fatal Exception: java.lang.NoSuchFieldError No static field DEVELOPER_ERRORS of type Lcom/facebook/LoggingBehavior; in class Lcom/facebook/LoggingBehavior; or its superclasses (declaration of 'com.facebook.LoggingBehavior' appears in base.apk) com.facebook.FacebookSdk.<clinit>

### ISSUE THREAD

**Issue by weishl110** [facebook/facebook-android-sdk#886]
Fatal Exception: java.lang.NoSuchFieldError
No static field DEVELOPER_ERRORS of type Lcom/facebook/LoggingBehavior; in class Lcom/facebook/LoggingBehavior; or its superclasses (declaration of 'com.facebook.LoggingBehavior' appears in base.apk)
com.facebook.FacebookSdk.<clinit>

com.facebook.android:facebook-login:5.13.0

**Comment by Mxiim** [comment]
Hello,
Please add steps how to reproduce this and reopen again. Also please update SDK to latest (8.2.0).
