### ISSUE TITLE
Feature Request: Limited login on Android?

### ISSUE THREAD

**Issue by hansemannn** [facebook/facebook-android-sdk#888]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

I would like to ask what the plans regarding the limited login on Android are. It's a great new feature on iOS, but having parity on the Android side would be a great win for the community!

**Comment by galonga** [comment]
Would be nice to see this feature.

**Comment by hansemannn** [comment]
Yes, it should remain active.

**Comment by hansemannn** [comment]
Yes, it should remain active...

**Comment by hansemannn** [comment]
Yes, it should remain active...

**Comment by panavenue** [comment]
Hi all. Thank you for the suggestion. Limited Login on Android is something on our radar. Will let the community know once we have more to share :)

**Comment by hansemannn** [comment]
Yes, it should remain active...

**Comment by galonga** [comment]
It is still a feature request for the Android SDK and should stay active.

**Comment by TepesLucian** [comment]
Any updates on this by any chance?
