### ISSUE TITLE
Facebook Audience Network ads crash on Android devices

### ISSUE THREAD

**Issue by roma7481** [facebook/facebook-android-sdk#892]
I see that Facebook Audience Network Native ads crash on Android devices for my users. The crash is happening on release version only. I am using the latest Facebook audience-network-sdk 6.2. I have apps with older sdk 5.7 and I don't see this issue. The crash is:

Fatal Exception: java.lang.NoSuchMethodError

No static method getSharedPreferences(Landroid/content/Context;)Landroid/content/SharedPreferences; in class Lcom/facebook/ads/internal/settings/AdSharedPreferences; or its super classes (declaration of 'com.facebook.ads.internal.settings.AdSharedPreferences' appears in /data/app/<app id>-1/base.apk) 

    com.facebook.ads.redexgen.X.4u.isTestMode (4u.java:12285)
    com.facebook.ads.internal.settings.AdInternalSettings.isTestMode (AdInternalSettings.java)
    com.facebook.ads.AdSettings.isTestMode (AdSettings.java)
    com.facebook.ads.redexgen.X.1m.A01 (1m.java:3656)
    com.facebook.ads.redexgen.X.SJ.A0D (SJ.java:52213)
    com.facebook.ads.redexgen.X.SJ.A0T (SJ.java:52288)
    com.facebook.ads.redexgen.X.SJ.A0U (SJ.java:52290)
    com.facebook.ads.redexgen.X.cD.A1U (cD.java:72218)
    com.facebook.ads.redexgen.X.Je.A00 (Je.java:40169)
    com.facebook.ads.redexgen.X.cD.loadAd (cD.java:72343)
    com.facebook.ads.NativeAdBase.loadAd (NativeAdBase.java)
    ads.NativeAdActivity.access$000 (NativeAdActivity.java)
	
Please help, couldn't find anything online.

**Comment by deniza** [comment]
hey @roma7481 . I am getting similar results in my application, mainly on huawei devices using various android versions/ API levels. Do you see a pattern on device models or API versions?

**Comment by deniza** [comment]
Also I highly recommend running an automated test on Firebase or similar platform. Today I ran a robot test using firebase automation panel and got crash reports while running on huawei devices. Give it a try.

**Comment by roma7481** [comment]
I see this crash on all devices on all of my apps.

**Comment by deniza** [comment]
Are you using any kind of mediation, or only facebook audience network?

**Comment by roma7481** [comment]
I am using  only facebook audience network. It happens after 5.7 version. I am currently using 5.7 version in my apps.

**Comment by roma7481** [comment]
Ok, I found the solution. 

We need to put 
-keep class com.facebook.ads.** { *; }

in Proguard settings

**Comment by ashaevy** [comment]
NoSuchMethodError usually happens because ProGuard mistakenly removes some method from the class (NoClassDefFoundError for classes). To confirm this you usually want to check if method exists before obfuscation / optimisation. Just drag and drop the library AAR into Android Studio and check if binary has the method. If the method is present, you need to change ProGuard configuration. Also use ProGuard logs to better understand if it removes some methods/classes.
AN SDK has included "consumer-rules.pro" file that should normally prevent this.

**Comment by roma7481** [comment]
Thanks for the explanation.
