### ISSUE TITLE
HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '<MY_APP_ID>' does not exist, cannot be loaded due to missing permissions, or does not support this operation.

### ISSUE THREAD

**Issue by jesper372** [facebook/facebook-android-sdk#900]
When running my Flutter app (that makes use of the ```flutter-facebook-auth plugin```), after a clean build, an exception is reported in Android (but not iOS):

> {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '<MY_APP_ID>' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}

The exception only occurs after a clean build, when the app starts; it does not occur when signing in with Facebook (which works). I've followed the instructions in the [plugin documentation](https://pub.dev/packages/flutter_facebook_auth#android) to the letter.

**I originally filed this issue on the repo for the above plugin**; however, the [response](https://github.com/darwin-morocho/flutter-facebook-auth/issues/47#issuecomment-776056570) was that this is actually an issue that needs to be resolved here.

**Comment by Mxiim** [comment]
Did you include the app_id in your Manifest as in step #4 https://developers.facebook.com/docs/facebook-login/android ?
If yes, create a sample project so we can reproduce this

**Comment by AmirDiafi** [comment]
+1

**Comment by ozanurkn** [comment]
+1

**Comment by OP4PCC** [comment]
Hi just get rid of this error, actually I was doing a mistake , when I was giving setPermission in that I was assigning wrong access permission. So, just check that permission carefully
like here 
 log_btn.setPermissions(Arrays.asList("email","user_birthday"));
you can also check on developer page  in app review section permission and features

**Comment by xros** [comment]
I am using Flutter with Android to build the app. Same error. Im sure that I added the api id in the AndroidManifest.xml.

I followed the tutorial here: https://developers.facebook.com/docs/facebook-login/android

I didn't even set any permission. 

`HttpStatus: 400, errorCode: 100, subErrorCode: 33. Object with ID '<the_app_id_number>' does not exist`

I am using this plugin, flutter_login_facebook with firebase

 https://pub.dev/packages/flutter_login_facebook
So weird.

**Comment by xros** [comment]
> 

Alright, i figured it out. You need to make your app mode **live**. You needs to provide info, url for polices. It depends on what app you created. Also you need to grant permissions to your app. Nicely done.

**Comment by mkssanudeep** [comment]
I have use Unity Facebook Sdk and I am getting the same error, anyone else got this ?

**Comment by Tharwat07** [comment]
Hi Everyone,
i tried to update "facebook_app_id" in app/src/main/res/values/strings.xml to facebook app id from facebook developers .. and this issus solved

**Comment by Hyprnx** [comment]
> > 
> 
> Alright, i figured it out. You need to make your app mode **live**. You needs to provide info, url for polices. It depends on what app you created. Also you need to grant permissions to your app. Nicely done.

exactly, everythings worked after i set the app to live mode
