### ISSUE TITLE
A bit of confusion around "latest release"

### ISSUE THREAD

**Issue by TWiStErRob** [facebook/facebook-android-sdk#918]
Tags: https://github.com/facebook/facebook-android-sdk/tags -> 9.1.0
Releases: https://github.com/facebook/facebook-android-sdk/releases -> 8.1.0
Changelog: https://github.com/facebook/facebook-android-sdk/blob/master/CHANGELOG.md -> 9.1.0
Maven Central: https://search.maven.org/artifact/com.facebook.android/facebook-android-sdk -> 9.0.0
Readme: https://github.com/facebook/facebook-android-sdk#installation -> 8.1.0

**Comment by linmx0130** [comment]
@TWiStErRob Thank you very much for raising this issue! For now tags,releases, changelog and maven central are all updated. Readme will be updated soon!

**Comment by TWiStErRob** [comment]
I just noticed that @facebook-sdk-bot was doing the releases before, looks like that stopped last November.
