### ISSUE TITLE
Poor change log

### ISSUE THREAD

**Issue by sergpetrov** [facebook/facebook-android-sdk#926]
I'm going to migrate on Facebook SDK v9 and I don't understand what exactly you changed. 
The Facebook Android SDK changelog is very poor https://github.com/facebook/facebook-android-sdk/blob/master/CHANGELOG.md
It has a single phrase `The default Graph API version is updated to v9.0` and that's all.

How are you supposing we should migrate to the new version? Should we review the all documentation of Graph API?

Btw, I already see an issue with `AppLinks.getTargetUrlFromInboundIntent(context, intent)` because this one doesn't exist in the v9, and nowhere it is described what it should be replaced with.

Please, do not be lazy, do a detailed changelog like iOS SDK.

**Comment by jingping2015** [comment]
Hi, thanks for report this issue. I think you can use bolts directly for this feature.  (https://github.com/BoltsFramework/Bolts-Android).

**Comment by likfe** [comment]
#1006

**Comment by jesphinpt** [comment]
BoltsFramework is a deprecated library. So we not prefer this to use in our apps?
(https://github.com/BoltsFramework/Bolts-Android).
