### ISSUE TITLE
App crash: Utility.java line 584 com.facebook.internal.Utility.clearCookiesForDomain

### ISSUE THREAD

**Issue by xiaoqian0408** [facebook/facebook-android-sdk#927]
This crash is reported by Firebase, here's the trace:

Caused by android.webkit.WebViewFactory$MissingWebViewPackageException
Failed to load WebView provider: No WebView installed

android.webkit.WebViewFactory.getWebViewContextAndSetProvider (WebViewFactory.java:339)
android.webkit.WebViewFactory.getProviderClass (WebViewFactory.java:402)
android.webkit.WebViewFactory.getProvider (WebViewFactory.java:252)
android.webkit.CookieManager.getInstance (CookieManager.java:47)
android.webkit.CookieSyncManager.sync (CookieSyncManager.java:112)
com.facebook.internal.Utility.clearCookiesForDomain (Utility.java:584)
com.facebook.internal.Utility.clearFacebookCookies (Utility.java:608)
com.facebook.login.WebLoginMethodHandler.getParameters (WebLoginMethodHandler.java:89)
com.facebook.login.CustomTabLoginMethodHandler.tryAuthorize (CustomTabLoginMethodHandler.java:93)
com.facebook.login.LoginClient.tryCurrentHandler (LoginClient.java:280)
com.facebook.login.LoginClient.tryNextHandler (LoginClient.java:233)
com.facebook.login.LoginClient.authorize (LoginClient.java:120)
com.facebook.login.LoginClient.startOrContinueAuth (LoginClient.java:101)
com.facebook.login.LoginFragment.onResume (LoginFragment.java:161)
androidx.fragment.app.Fragment.performResume (Fragment.java:2748)
androidx.fragment.app.FragmentStateManager.resume (FragmentStateManager.java:373)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1211)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1368)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1446)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1509)
androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2637)
androidx.fragment.app.FragmentManager.dispatchResume (FragmentManager.java:2601)
androidx.fragment.app.FragmentController.dispatchResume (FragmentController.java:269)
androidx.fragment.app.FragmentActivity.onResumeFragments (FragmentActivity.java:478)
androidx.fragment.app.FragmentActivity.onPostResume (FragmentActivity.java:467)
android.app.Activity.performResume (Activity.java:7974)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:4253)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4295)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2056)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7557)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:937)

It seems to be caused web view, but the crash happened when com.facebook.internal.Utility.clearCookiesForDomain (Utility.java:584) is called, shouldn't we avoid such crash in the sdk?

**Comment by jingping2015** [comment]
Hi, Could you tried again with latest SDK? Let us know if you still facing the same issue.

**Comment by jingping2015** [comment]
Close since no response.
