### ISSUE TITLE
Weird code that probably induces bugs in initializeIfNotInitialized()

### ISSUE THREAD

**Issue by agGitHub** [facebook/facebook-android-sdk#928]
Hi,

I noticed a weird code [here](https://github.com/facebook/facebook-android-sdk/blob/08cebb47da4631b751d65ad30f489864b78a46f3/facebook-core/src/main/java/com/facebook/UserSettingsManager.java) in initializeIfNotInitialized().

It is written:

```
public static void initializeIfNotInitialized() {
    if (!FacebookSdk.isInitialized()) {
      return;
    }
```

Shouldn't it be:

`if (FacebookSdk.isInitialized())`

instead?

Thanks.

**Comment by linmx0130** [comment]
Hi @agGitHub! Thanks for raising this issue.

This `initializeIfNotInitialized()` method is to initialize `UserSettingsManager`, not `FacebookSdk`. This process can only be done after the initialization of `FacebookSdk`.
