### ISSUE TITLE
Logging in this app with facebook is not available this time

### ISSUE THREAD

**Issue by hieuseesaa** [facebook/facebook-android-sdk#932]
Hello

I get error : "logging in this app with facebook is not available this time"
Condition: 
+ App facebook not install
+ version sdk facebook: v9.0.0 and v9.1.0

it worked: (4-5]

please let me know the cause of the above error. Thank you very much.

**Comment by CFFChi** [comment]
May I ask what is your appID?

**Comment by hieuseesaa** [comment]
@CFFChi 
Sorry. the appid is the client's. 
Do you think of any reasons?

**Comment by kienvn** [comment]
Same problem when i auth with browser on Nox

**Comment by hieuseesaa** [comment]
@kienvn 
Ông có tài khoản facebook test ra lỗi này ko. Gửi tôi mượn test. 
Tài khoản của khách hàng bị lỗi nên ko xin đc.

**Comment by kienvn** [comment]
> @kienvn
> Ông có tài khoản facebook test ra lỗi này ko. Gửi tôi mượn test.
> Tài khoản của khách hàng bị lỗi nên ko xin đc.

Thử auth không dùng app Facebook trên Nox là bị thôi

**Comment by hieuseesaa** [comment]
@kienvn 
Đang ko dùng app mà.
tài khoản nào cũng bị à. tôi test thì ko sao. nhưng khách hàng test thì bị. khách hàng báo là tài khoản mới thì ko bị. 
Nghĩ là do tài khoản. Mà hiện tại thì k có tài khoản để debug nên k tìm đc lỗi. Có share đc ko?

**Comment by kienvn** [comment]
> @kienvn
> Đang ko dùng app mà.
> tài khoản nào cũng bị à. tôi test thì ko sao. nhưng khách hàng test thì bị. khách hàng báo là tài khoản mới thì ko bị.
> Nghĩ là do tài khoản. Mà hiện tại thì k có tài khoản để debug nên k tìm đc lỗi. Có share đc ko?

![image](https://user-images.githubusercontent.com/3658115/114361406-4d5dd600-9ba0-11eb-9f65-5961e9a439fe.png)
Tài khoản của tôi mở trên trình duyệt của Nox login là bị luôn rồi, không cần auth qua app

**Comment by hieuseesaa** [comment]
@kienvn Vậy à. t cứ tưởng phải bấm vào login nó mới bị lỗi trên cơ. 

Ông đã thêm cái này vào chưa 

```
   <queries>
        <package android:name="com.facebook.katana" />
    </queries>

```

Thêm ở giữa **manifest** và **application**

**Comment by hieuseesaa** [comment]
@kienvn tình hình sao rồi ông. có cách giải quyết nào ko?.
