### ISSUE TITLE
Facebook login LS-NONCE reset code

### ISSUE THREAD

**Issue by yiann0s** [facebook/facebook-android-sdk#955]
While a user is trying to log in to our app using Facebook login, there is the option of reminding the login password, by clicking the "Forgot Password?" .
After this step, the user is prompted to enter his/her mobile phone or email or full name. Nevertheless, after filling out with either the phone or email , the message sent does not contain a 6 character code but the String LS-NONCE (check screenshot below). Same thing happens when a SMS is received.
While noticing this happening on the 9.1.0 Facebook SDK, I tried rolling back to 6.5.0 with the problem still persisting , though.
If you need any more information on this issue, I am willing to provide them.
Thank you for your time and patience.
![email_message](https://user-images.githubusercontent.com/16455421/114840598-a1a2c900-9ddf-11eb-81ac-b84715e853ef.PNG)

**Comment by jingping2015** [comment]
Hi, Thanks for report this issue, but this issue is not about SDK, you can check or ask this question in Facebook help community. https://www.facebook.com/help/community

**Comment by D4VID0x2** [comment]
I have the same issue.
Unable to use messenger.
The Facebook help community doesn't exist, just redirects to the normal help which is also absolutely useless.

**Comment by yv0nn** [comment]
Is there some answer to the issue or just a new account creation is the solution? Thanks

**Comment by D4VID0x2** [comment]
There is no answer.
The solution is to not use facebook. Use Signal instead.
