### ISSUE TITLE
SDK usage banned api

### ISSUE THREAD

**Issue by kailash11111** [facebook/facebook-android-sdk#961]
Hi Team,

Currently one security team has done security audit of our project and they have suggested that in below classes banned api is being used.

1. FBSDKCrypt o.m- Line No-166
2. FBSDKCrypt o.m- Line No-168
3. FBSDKCrypt o.m- Line No-185
4. FBSDKCrypt o.m- Line No-270
5. FBSDKCrypt o.m- Line No-274
6. FBSDKCrypt o.m- Line No-277

Can you guys please have a look into this.

Cause: Insufficient Encryption
Impact: Source Code Compromise

Please let us know if we can get a updated sdk for the same after this change.Thanks in advance!!!

**Comment by linmx0130** [comment]
It seems that what you mentioned is in iOS SDK. Could you post in Facebook iOS SDK repo?
