### ISSUE TITLE
Feature Request: remove deprecated android-kotlin-extensions

### ISSUE THREAD

**Issue by plastiv** [facebook/facebook-android-sdk#962]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

android-kotlin-extensions is deprecated https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html and will be removed from upcoming Kotlin release in September 2021. 

Having transitive `android-kotlin-extensions-runtime` dependency from facebook sdk brings additional challenges during migration.

## Expected Results

Facebook SDK doesn't bundle android-kotlin-extensions.

## Code Samples & Details

```
+--- com.facebook.android:facebook-login:9.1.1
|    +--- com.facebook.android:facebook-core:9.1.1
|    |    +--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.10 -> 1.4.32 (*)
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    +--- com.android.installreferrer:installreferrer:1.0 -> 2.2
|    |    +--- androidx.core:core-ktx:1.3.2 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10 -> 1.4.32 (*)
```

**Comment by tonyartch** [comment]
Quien podria explicarme que esta pasandon?? Sorri

**Comment by linmx0130** [comment]
Hi @plastiv! Thank you very much for raising this issue! 

Commit 3d97759431cf2f4f1aee1176f5c6c5c522dabc0e removes the dependency on `android-kotlin-extensions` and the change will be in the next Facebook Android SDK release. We expect to release it in June.

Again, we really appreciate your issue that helps us to improve our SDK quality!
