### ISSUE TITLE
implementation 'com.facebook.android:facebook-android-sdk:8.1.0' Does it enable ads also?

### ISSUE THREAD

**Issue by paul035** [facebook/facebook-android-sdk#963]
I just want to know does this enable ads services also, as it says sdk(everything).
// Facebook Android SDK (everything)
implementation 'com.facebook.android:facebook-android-sdk:8.1.0'

**Comment by xilosada** [comment]
Hi @paul035, please follow the Audience Network documentation to monetize your app inventory. The audience network SDK is distributed independently. https://developers.facebook.com/docs/audience-network/
