### ISSUE TITLE
GraphMethodException Facebook Login Error with App ID

### ISSUE THREAD

**Issue by ArcherEmiya05** [facebook/facebook-android-sdk#964]
`Facebook Login v9.1.1`

This is a very weird error during the launch of the app with splash and some overboard screen before going to login screen so no Facebook API call yet is being perform but there is this error that frequently shows

`
{HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID 'MY_APP_ID' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}`

I checked the App ID and it is correct, I also check the Facebook Log in implementation if there is any breaking changes but everything is just the same. It seems users can still login despite the error above but when can we expect this to be removed because its annoying and frustrating if false positive. Imagine trying to solve a fake problem.

There are previous issue related to this but was closed out of nowhere.

**Comment by ArcherEmiya05** [comment]
It seems the error was gone after going to ` **Live Mode**` anyone please verify so I can close this issue.

**Comment by linmx0130** [comment]
Hi @ArcherEmiya05. Thanks for raising the issue but we can only handle the issues with all checklist items checked. 

Also it looks like the app is declared its app id as `"MY_APP_ID"`, which is invalid. Could you mind having a double check?
