### ISSUE TITLE
How to get the user's name

### ISSUE THREAD

**Issue by Tanyk2004** [facebook/facebook-android-sdk#970]
I have created an object of the class LoginResult as per the facebook dev documentation. Now from that how can I get the logged in user's name to be displayed in my activity.

**Comment by linmx0130** [comment]
You can follow https://developers.facebook.com/docs/facebook-login/android/accesstokens for the details.
You can also check login sample at [samples/FBLoginSample/](https://github.com/facebook/facebook-android-sdk/tree/master/samples/FBLoginSample).
