### ISSUE TITLE
Question:  How to use multiple query parameters  in Facebook AppLinks?

### ISSUE THREAD

**Issue by Sguarino93** [facebook/facebook-android-sdk#972]
In our current project we are using pathPattern to specify multiple query parameters in a deeplink.

![image](https://user-images.githubusercontent.com/56177522/122992787-e701ea80-d37c-11eb-9439-bae58563b38b.png)

But so far i've been unable to find any AppLinks documentation regarding generation of a URI with 2 ids.

**Comment by CROCDC** [comment]
I have the same question, the documentation is a disaster, it does not explain anything about this scenario.

**Comment by CROCDC** [comment]
Hello, do you have an update regarding this issue?
