### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by amirmhrzan123** [facebook/facebook-android-sdk#978]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)

### Goals

OnActivityResult is deprecated in latest android version. What need to be done instead of overriding callback in onactivity result in order to pass it onto login manager.

### Expected results

New documentation for new android updates

### Code samples & details

```java
This is deprecated.  
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        callbackManager.onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }
```

**Comment by bulutaysarac** [comment]
This issue should be fixed as soon as possible.

**Comment by sanchi0204** [comment]
Can I take this up?

**Comment by xilosada** [comment]
Duplicated https://github.com/facebook/facebook-android-sdk/issues/875. This issue will be solved in the v12(Oct)
